(()=>{
  const sb=window.supabase.createClient(window.MADA_SUPABASE_URL,window.MADA_SUPABASE_KEY);
  const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const $=id=>document.getElementById(id);
  const tabs=[
    ['notifications','🔔','مركز الإشعارات'],['security','🛡️','الأمان والحسابات'],
    ['announcement','📣','إعلان للجميع'],['support','🎟️','الدعم والشكاوى'],
    ['backup','🗄️','النسخ الاحتياطي'],['errors','⚠️','أخطاء النظام'],['admin-messages','📨','رسائل المستخدمين']
  ];
  const style=document.createElement('style');style.textContent=`
  .more-sep{grid-column:1/-1;margin:4px 0;padding:7px 8px;color:#7c8798;font-size:12px;font-weight:900;border-top:1px solid #edf1f5}
  .more-panel{width:100%;min-width:0}.more-panel .card{width:100%;overflow:hidden}.more-actions{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.more-actions button{border:0;border-radius:10px;padding:9px 12px;font-weight:800;cursor:pointer}.more-primary{background:#2563eb;color:#fff}.more-muted{background:#eef2f7;color:#263147}.more-danger{background:#fff0f0;color:#b42318}.more-form{display:grid;gap:10px}.more-form input,.more-form textarea,.more-form select{width:100%;padding:11px;border:1px solid #dde4ed;border-radius:12px;background:#fff}.more-form textarea{min-height:130px;resize:vertical}.more-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:10px}.more-item{padding:14px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.more-status{display:inline-block;padding:5px 9px;border-radius:20px;font-size:12px;font-weight:800}.more-ok{background:#eaf8f0;color:#087443}.more-warn{background:#fff8e6;color:#9a6700}.more-bad{background:#fff0f0;color:#b42318}.more-code{font-family:monospace;white-space:pre-wrap;word-break:break-word;font-size:12px;background:#f7f9fc;padding:10px;border-radius:10px;direction:ltr;text-align:left}
  @media(max-width:720px){aside{grid-template-columns:repeat(3,minmax(0,1fr))!important}.more-grid{grid-template-columns:1fr 1fr}.more-item{padding:11px}.more-sep{font-size:11px}}
  @media(max-width:430px){.more-grid{grid-template-columns:1fr}}
  body.dark .more-sep{border-color:#27364e;color:#9aa8bc}body.dark .more-item,body.dark .more-form input,body.dark .more-form textarea,body.dark .more-form select{background:#121d30;border-color:#2b3b55;color:#edf3ff}body.dark .more-code{background:#0d1728}
  `;document.head.appendChild(style);
  const tableTry=async names=>{for(const t of names){try{const r=await sb.from(t).select('*',{count:'exact',head:true});if(!r.error)return t}catch(e){}}return null};
  function addTabs(){const aside=document.querySelector('aside');if(!aside||aside.querySelector('.more-sep'))return;const sep=document.createElement('div');sep.className='more-sep';sep.textContent='باقي أدوات الإدارة';aside.appendChild(sep);tabs.forEach(([id,icon,label])=>{const b=document.createElement('button');b.dataset.moreTab=id;b.innerHTML=`<i>${icon}</i> ${label}`;b.onclick=()=>render(id);aside.appendChild(b)})}
  function loading(title){$('content').innerHTML=`<div class="card"><h2>${title}</h2><p>جاري التحميل…</p></div>`}
  async function render(id){document.querySelectorAll('aside button').forEach(b=>b.classList.toggle('active',b.dataset.moreTab===id));const map={notifications:['🔔 مركز الإشعارات',notifications],security:['🛡️ الأمان والحسابات',security],announcement:['📣 إرسال إعلان لجميع المستخدمين',announcement],support:['🎟️ إدارة الدعم والشكاوى',support],backup:['🗄️ النسخ الاحتياطي واستعادة البيانات',backup],errors:['⚠️ مركز مراقبة النظام والأخطاء',errors], 'admin-messages':['📨 رسائل الأدمن للمستخدمين',messages]};loading(map[id]?.[0]||'الإدارة');return map[id]?.[1]?.()}
  async function notifications(){const t=await tableTry(['notifications','user_notifications','admin_notifications']);if(!t){$('content').innerHTML=`<div class="more-panel"><div class="card"><h2>🔔 مركز الإشعارات</h2><p>لا يوجد جدول إشعارات متاح حاليًا. الواجهة جاهزة، ولن يتم إنشاء جدول أو حذف بيانات تلقائيًا.</p></div></div>`;return}const {data,error}=await sb.from(t).select('*').order('created_at',{ascending:false}).limit(100);if(error)return showErr('مركز الإشعارات',error);$('content').innerHTML=`<div class="more-panel"><div class="card"><h2>🔔 مركز الإشعارات</h2><p class="mini">الجدول المستخدم: ${esc(t)}</p><div class="more-grid">${(data||[]).map(x=>`<article class="more-item"><b>${esc(x.title||x.subject||'إشعار')}</b><p>${esc(x.body||x.message||x.content||'')}</p><small>${x.created_at?new Date(x.created_at).toLocaleString('ar-EG'):''}</small></article>`).join('')||'<p>لا توجد إشعارات.</p>'}</div></div></div>`}
  async function security(){const [u,b,r]=await Promise.all([countSafe('profiles'),countSafe('profiles',q=>q.eq('is_banned',true)),countSafe('reports',q=>q.eq('status','pending'))]);$('content').innerHTML=`<div class="more-panel"><div class="card"><h2>🛡️ الأمان ومكافحة الحسابات الوهمية</h2><div class="more-grid"><div class="more-item"><b>إجمالي الحسابات</b><h2>${u}</h2></div><div class="more-item"><b>الحسابات المحظورة</b><h2>${b}</h2></div><div class="more-item"><b>بلاغات معلقة</b><h2>${r}</h2></div></div><div class="notice"><b>فحص أولي:</b> راقب الحسابات الجديدة، تكرار البلاغات، والحظر. أي إجراء حظر فعلي يظل من قسم «الحظر» الموجود أصلًا.</div></div></div>`}
  async function countSafe(t,filter){let q=sb.from(t).select('*',{count:'exact',head:true});if(filter)q=filter(q);const r=await q;return r.error?0:(r.count||0)}
  async function announcement(){$('content').innerHTML=`<div class="more-panel"><div class="card"><h2>📣 إرسال إعلان لجميع المستخدمين</h2><p>اكتب الإعلان ثم أرسله عبر جدول الإشعارات المتاح في مشروعك.</p><div class="more-form"><input id="annTitle" placeholder="عنوان الإعلان"><textarea id="annBody" placeholder="نص الإعلان"></textarea><select id="annType"><option value="announcement">إعلان</option><option value="system">تنبيه نظام</option></select><div class="more-actions"><button class="more-primary" onclick="window.madaSendAnnouncement()">📣 إرسال</button></div><div id="annMsg"></div></div></div></div>`}
  window.madaSendAnnouncement=async()=>{const title=$('annTitle')?.value.trim(),body=$('annBody')?.value.trim(),type=$('annType')?.value||'announcement';if(!title||!body){$('annMsg').innerHTML='<span class="more-status more-warn">اكتب العنوان والنص أولًا.</span>';return}const t=await tableTry(['notifications','admin_notifications','user_notifications']);if(!t){$('annMsg').innerHTML='<span class="more-status more-bad">لا يوجد جدول إشعارات مناسب في قاعدة البيانات.</span>';return}const payloads=[{title,body,type},{title,message:body,type},{title,content:body,type}];let last=null;for(const p of payloads){const r=await sb.from(t).insert(p);if(!r.error){$('annMsg').innerHTML='<span class="more-status more-ok">تم إرسال الإعلان.</span>';return}last=r.error}$('annMsg').innerHTML=`<span class="more-status more-bad">تعذر الإرسال: ${esc(last?.message||'خطأ')}</span>`};
  async function support(){const t=await tableTry(['support_tickets','tickets','complaints','support_requests']);if(!t){$('content').innerHTML=`<div class="more-panel"><div class="card"><h2>🎟️ إدارة الدعم والشكاوى</h2><p>لا يوجد جدول دعم/شكاوى معروف حاليًا. الواجهة جاهزة، ولم يتم إنشاء أي جدول تلقائيًا.</p></div></div>`;return}const {data,error}=await sb.from(t).select('*').order('created_at',{ascending:false}).limit(100);if(error)return showErr('الدعم والشكاوى',error);$('content').innerHTML=`<div class="more-panel"><div class="card"><h2>🎟️ إدارة الدعم والشكاوى</h2><p class="mini">الجدول: ${esc(t)}</p><div class="more-grid">${(data||[]).map(x=>`<article class="more-item"><b>${esc(x.subject||x.title||'طلب دعم')}</b><p>${esc(x.message||x.body||x.description||'')}</p><span class="more-status ${String(x.status||'').toLowerCase().includes('open')||x.status==='pending'?'more-warn':'more-ok'}">${esc(x.status||'غير محدد')}</span></article>`).join('')||'<p>لا توجد طلبات.</p>'}</div></div></div>`}
  async function backup(){const tables=['profiles','posts','comments','reports','subscriptions','payments','admin_audit_log'];$('content').innerHTML=`<div class="more-panel"><div class="card"><h2>🗄️ النسخ الاحتياطي واستعادة البيانات</h2><p>النسخة الاحتياطية هنا تصدّر البيانات التي يسمح بها RLS إلى ملف JSON. لا يتم حذف أو استبدال أي بيانات.</p><div class="more-actions"><button class="more-primary" onclick="window.madaCreateBackup()">⬇️ إنشاء نسخة احتياطية</button></div><div id="backupMsg"></div></div></div>`;window.madaCreateBackup=async()=>{const out={created_at:new Date().toISOString(),tables:{}};for(const t of tables){const r=await sb.from(t).select('*').limit(5000);out.tables[t]=r.error?{error:r.error.message,data:[]}:{data:r.data||[]}}const blob=new Blob([JSON.stringify(out,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`mada-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);$('backupMsg').innerHTML='<span class="more-status more-ok">تم إنشاء ملف النسخة الاحتياطية.</span>'}}
  async function errors(){const t=await tableTry(['system_errors','error_logs','app_errors','admin_errors']);if(!t){$('content').innerHTML=`<div class="more-panel"><div class="card"><h2>⚠️ مركز مراقبة النظام والأخطاء</h2><p>لا يوجد جدول أخطاء معروف حاليًا. تم ترك النظام بدون أي تعديل تلقائي.</p><div class="notice">يمكن استخدام «اختبار الوظائف» الموجود أصلًا لفحص الاتصال.</div></div></div>`;return}const {data,error}=await sb.from(t).select('*').order('created_at',{ascending:false}).limit(100);if(error)return showErr('أخطاء النظام',error);$('content').innerHTML=`<div class="more-panel"><div class="card"><h2>⚠️ مركز مراقبة النظام والأخطاء</h2><p class="mini">الجدول: ${esc(t)}</p>${(data||[]).map(x=>`<div class="more-item" style="margin:8px 0"><b>${esc(x.level||x.severity||'ERROR')}</b> — ${esc(x.message||x.error||x.details||'')}</div>`).join('')||'<p>لا توجد أخطاء مسجلة.</p>'}</div></div>`}
  async function messages(){const t=await tableTry(['admin_messages','messages','user_messages']);if(!t){$('content').innerHTML=`<div class="more-panel"><div class="card"><h2>📨 رسائل الأدمن للمستخدمين</h2><p>لا يوجد جدول رسائل إدارية معروف حاليًا. لم يتم إنشاء أي جدول تلقائيًا.</p></div></div>`;return}const {data,error}=await sb.from(t).select('*').order('created_at',{ascending:false}).limit(100);if(error)return showErr('رسائل الأدمن',error);$('content').innerHTML=`<div class="more-panel"><div class="card"><h2>📨 رسائل الأدمن للمستخدمين</h2><p class="mini">الجدول: ${esc(t)}</p><div class="more-grid">${(data||[]).map(x=>`<article class="more-item"><b>${esc(x.subject||x.title||'رسالة')}</b><p>${esc(x.body||x.message||x.content||'')}</p><small>${esc(x.user_id||x.recipient_id||x.to_user_id||'')}</small></article>`).join('')||'<p>لا توجد رسائل.</p>'}</div></div></div>`}
  function showErr(title,e){$('content').innerHTML=`<div class="card"><h2>${title}</h2><p>${esc(e?.message||'حدث خطأ')}</p><div class="more-code">${esc(JSON.stringify(e||{},null,2))}</div></div>`}
  function boot(){addTabs()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
