const $=id=>document.getElementById(id);const HASH='d97765f2c61b4a77440895c1cfe9e2b761d174b03d1e2cbdf61b917493cd3946';
async function sha(s){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))].map(x=>x.toString(16).padStart(2,'0')).join('')}
$('loginBtn').onclick=async()=>{const u=$('u').value.trim(),p=$('p').value;if(u==='admin1'&&await sha(p)===HASH){sessionStorage.setItem('mada_admin','1');openDash()}else alert('بيانات الدخول غير صحيحة')};function openDash(){if(sessionStorage.getItem('mada_admin')!=='1')return; $('login').hidden=true;$('dash').hidden=false;tab('overview')}$('logout').onclick=()=>{sessionStorage.removeItem('mada_admin');location.reload()};document.querySelectorAll('aside button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
function stats(){const posts=JSON.parse(localStorage.getItem('mada_posts')||'[]'),user=JSON.parse(localStorage.getItem('mada_user')||'null');return{posts,user,likes:posts.reduce((n,p)=>n+(p.likes||0),0),comments:posts.reduce((n,p)=>n+(p.comments?.length||0),0)}}
function tab(t){const s=stats();let h='';if(t==='overview')h=`<h2>📊 الإحصائيات</h2><div class="grid"><div class="card">المستخدم الحالي<div class="num">${s.user?'1':'0'}</div></div><div class="card">المنشورات<div class="num">${s.posts.length}</div></div><div class="card">الإعجابات<div class="num">${s.likes}</div></div><div class="card">التعليقات<div class="num">${s.comments}</div></div><div class="card">Premium<div class="num">${localStorage.getItem('mada_premium')==='1'?'1':'0'}</div></div></div>`;
if(t==='users')h=`<h2>👥 المستخدمون</h2><div class="toolbar"><input placeholder="بحث..."></div><table class="table"><tr><th>الاسم</th><th>البريد</th><th>الحالة</th><th>إجراء</th></tr>${s.user?`<tr><td>${esc(s.user.name)}</td><td>${esc(s.user.email)}</td><td><span class="ok">نشط</span></td><td><button class="danger" onclick="banUser()">حظر</button></td></tr>`:'<tr><td colspan="4">لا يوجد مستخدم محلي</td></tr>'}</table>`;
if(t==='posts')h=`<h2>📝 إدارة المنشورات</h2><div class="grid">${s.posts.map((p,i)=>`<div class="card"><b>${esc(p.name)}</b><p>${esc(p.text||'منشور بصورة')}</p><button class="danger" onclick="deletePost(${i})">حذف</button></div>`).join('')||'<div class="card">لا توجد منشورات</div>'}</div>`;
if(t==='reports')h=`<h2>🚩 البلاغات</h2><div class="card"><p>نظام البلاغات جاهز للربط بقاعدة البيانات.</p><span class="badge">0 بلاغات معلقة</span></div>`;
if(t==='premium')h=`<h2>💎 Premium</h2><div class="card"><h3>خطة Mada Premium</h3><p>السعر: <b>${localStorage.getItem('mada_price')||'99'} جنيه / شهر</b></p><p>بدون إعلانات • شارة Premium • أدوات إضافية • أولوية الدعم</p><button class="save" onclick="togglePremium()">${localStorage.getItem('mada_premium')==='1'?'إلغاء Premium':'تفعيل Premium تجريبي'}</button></div>`;
if(t==='bans')h=`<h2>⛔ الحظر</h2><div class="card">إدارة قائمة الحسابات المحظورة وربطها بقاعدة البيانات لاحقًا.</div>`;
if(t==='payments')h=`<h2>💳 المدفوعات والاشتراكات</h2><div class="notice">مهم: لا تضع PIN أو OTP أو كلمة مرور المحفظة هنا. هذه البيانات السرية يجب ألا تدخل في الموقع.</div><div class="grid"><div class="card"><h3>📱 محفظة كاش</h3><p>دفع يدوي/تاجر: <b>${esc(localStorage.getItem('cash_number')||'غير مضبوط')}</b></p></div><div class="card"><h3>⚡ InstaPay</h3><p>IPA: <b>${esc(localStorage.getItem('instapay_ipa')||'غير مضبوط')}</b></p></div><div class="card"><h3>🏦 الحساب البنكي</h3><p>اسم البنك: <b>${esc(localStorage.getItem('bank_name')||'غير مضبوط')}</b></p><p>IBAN: <b>${esc(localStorage.getItem('bank_iban')||'غير مضبوط')}</b></p></div></div><p>للدفع الآلي الحقيقي نحتاج حساب تاجر/مزود دفع وواجهة خادم للتحقق من العملية، وليس مجرد تحويل يدوي.</p>`;
if(t==='settings')h=`<h2>⚙️ الإعدادات</h2><div class="form card"><label>سعر Premium الشهري</label><input id="price" value="${localStorage.getItem('mada_price')||'99'}"><label>رقم محفظة كاش لاستقبال الاشتراكات</label><input id="cash" value="${localStorage.getItem('cash_number')||''}" placeholder="01xxxxxxxxx"><label>InstaPay IPA</label><input id="ipa" value="${localStorage.getItem('instapay_ipa')||''}" placeholder="name@instapay"><label>اسم البنك</label><input id="bank" value="${localStorage.getItem('bank_name')||''}"><label>IBAN</label><input id="iban" value="${localStorage.getItem('bank_iban')||''}><button class="save" onclick="saveSettings()">حفظ الإعدادات</button></div>`;$('content').innerHTML=h}
function saveSettings(){localStorage.setItem('mada_price',$('price').value);localStorage.setItem('cash_number',$('cash').value);localStorage.setItem('instapay_ipa',$('ipa').value);localStorage.setItem('bank_name',$('bank').value);localStorage.setItem('bank_iban',$('iban').value);alert('تم حفظ الإعدادات على هذا الجهاز');tab('payments')}
function togglePremium(){localStorage.setItem('mada_premium',localStorage.getItem('mada_premium')==='1'?'0':'1');tab('premium')}function deletePost(i){const a=JSON.parse(localStorage.getItem('mada_posts')||'[]');a.splice(i,1);localStorage.setItem('mada_posts',JSON.stringify(a));tab('posts')}function banUser(){localStorage.setItem('mada_banned','1');alert('تم وضع المستخدم في قائمة الحظر التجريبية');tab('bans')}function esc(s){return String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]))}openDash();