/* Mada Admin: Premium settings and subscription requests */
(function(){
 const {createClient}=window.supabase; const sb=createClient(window.MADA_SUPABASE_URL,window.MADA_SUPABASE_KEY);
 const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
 async function isAdmin(){const {data:{session}}=await sb.auth.getSession();if(!session)return false;const {data:p}=await sb.from('profiles').select('role,is_banned').eq('id',session.user.id).maybeSingle();return p?.role==='admin'&&!p?.is_banned}
 async function render(){if(!(await isAdmin()))return;const c=$('content');c.innerHTML='<div class="card">جاري تحميل Premium…</div>';const [{data:s},{data:r}]=await Promise.all([sb.from('admin_settings').select('*').eq('id',true).maybeSingle(),sb.from('subscription_requests').select('id,user_id,transaction_ref,receipt_image_url,status,created_at,profiles(display_name,username)').order('created_at',{ascending:false}).limit(100)]);c.innerHTML=`<h2>💎 Premium</h2><div class="card admin-premium-settings"><h3>إعدادات الاشتراك</h3><label>📱 رقم المحفظة</label><input id="premiumWallet" value="${esc(s?.cash_wallet)}" placeholder="01xxxxxxxxx"><label>💰 سعر الاشتراك بالجنيه</label><input id="premiumPrice" type="number" min="0" step="0.01" value="${s?.subscription_price_egp??99}"><button class="save" id="savePremiumSettings">💾 حفظ</button><p id="premiumSaveMsg"></p></div><h3>طلبات Premium</h3><div class="grid">${(r||[]).map(x=>`<div class="card request-card"><b>${esc(x.profiles?.display_name||x.profiles?.username||'مستخدم')}</b><p>رقم العملية: <strong>${esc(x.transaction_ref||'-')}</strong></p><p>الحالة: ${esc(x.status)}</p>${x.receipt_image_url?`<a href="${esc(x.receipt_image_url)}" target="_blank" rel="noopener"><img class="receipt" src="${esc(x.receipt_image_url)}" alt="إيصال الدفع"></a>`:''}${x.status==='pending'?`<div><button class="approve" data-id="${x.id}" data-user="${x.user_id}">قبول</button><button class="danger reject" data-id="${x.id}">رفض</button></div>`:''}</div>`).join('')||'<div class="card">لا توجد طلبات.</div>'}</div>`;
  $('savePremiumSettings').onclick=async()=>{const {data:{session}}=await sb.auth.getSession();const {error}=await sb.from('admin_settings').update({cash_wallet:$('premiumWallet').value.trim()||null,subscription_price_egp:Number($('premiumPrice').value),updated_at:new Date().toISOString(),updated_by:session.user.id}).eq('id',true);$('premiumSaveMsg').textContent=error?'تعذر الحفظ.':'✅ تم حفظ الإعدادات.'};
  c.querySelectorAll('.approve').forEach(b=>b.onclick=()=>review(b.dataset.id,b.dataset.user,'approved'));c.querySelectorAll('.reject').forEach(b=>b.onclick=()=>review(b.dataset.id,null,'rejected'));
 }
 async function review(id,userId,status){if(!(await isAdmin()))return alert('غير مصرح');const {data:{session}}=await sb.auth.getSession();const patch={status,reviewed_at:new Date().toISOString(),reviewed_by:session.user.id};const {error}=await sb.from('subscription_requests').update(patch).eq('id',id);if(error)return alert('تعذر تحديث الطلب: '+error.message);if(status==='approved'&&userId){const {error:e}=await sb.from('profiles').update({is_premium:true,badge:'diamond'}).eq('id',userId);if(e)return alert('تم قبول الطلب لكن تعذر تفعيل Premium: '+e.message)}render();}
 window.madaAdminPremium=render;document.addEventListener('DOMContentLoaded',()=>{const aside=document.querySelector('#dash aside');if(!aside)return;const b=document.createElement('button');b.dataset.tab='premium-requests';b.textContent='💎 طلبات Premium';b.onclick=render;aside.appendChild(b);});
})();