(function(){
  const {createClient}=window.supabase; const sb=createClient(window.MADA_SUPABASE_URL,window.MADA_SUPABASE_KEY); const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  async function isAdmin(){const{data:{session}}=await sb.auth.getSession();if(!session)return false;const{data:p}=await sb.from('profiles').select('role,is_banned').eq('id',session.user.id).single();return p?.role==='admin'&&!p.is_banned}
  async function openAdmin(){if(!(await isAdmin()))return alert('هذه الصفحة متاحة للمسؤولين فقط.');showModal('⚙️ لوحة إدارة Mada',`<div class="inline-admin"><div class="admin-inline-nav"><button data-a="overview">📊 الرئيسية</button><button data-a="users">👥 المستخدمون</button><button data-a="posts">📝 المنشورات</button><button data-a="reports">🚩 البلاغات</button><button data-a="friends">🤝 المجتمع</button></div><div id="inlineAdminContent" class="inline-admin-content"><div class="empty">جاري التحميل…</div></div></div>`);document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>render(b.dataset.a));render('overview')}
  async function count(t,filter){let q=sb.from(t).select('*',{count:'exact',head:true});if(filter)q=filter(q);const{count}=await q;return count||0}
  async function render(tab){const box=$('inlineAdminContent');if(!box)return;box.innerHTML='<div class="empty">جاري التحميل…</div>';if(tab==='overview'){const[a,b,c,d]=await Promise.all([count('profiles'),count('posts'),count('post_likes'),count('comments')]);box.innerHTML=`<div class="grid"><div class="card stat-card"><span>👥 المستخدمون</span><b class="num">${a}</b></div><div class="card stat-card"><span>📝 المنشورات</span><b class="num">${b}</b></div><div class="card stat-card"><span>👍 الإعجابات</span><b class="num">${c}</b></div><div class="card stat-card"><span>💬 التعليقات</span><b class="num">${d}</b></div></div>`}else if(tab==='users'){const{data}=await sb.from('profiles').select('id,display_name,username,role,is_banned,created_at').order('created_at',{ascending:false}).limit(100);box.innerHTML=`<div class="card"><div class="table-scroll"><table class="table"><tr><th>المستخدم</th><th>الدور</th><th>الحالة</th></tr>${(data||[]).map(x=>`<tr><td><b>${esc(x.display_name||'مستخدم')}</b><br><small>@${esc(x.username||'-')}</small></td><td>${x.role==='admin'?'👑 مسؤول':'مستخدم'}</td><td>${x.is_banned?'⛔ محظور':'🟢 نشط'}</td></tr>`).join('')}</table></div></div>`}else if(tab==='posts'){const{data}=await sb.from('posts').select('id,body,media_url,created_at,profiles(display_name)').order('created_at',{ascending:false}).limit(60);box.innerHTML=(data||[]).map(x=>`<article class="card post"><b>${esc(x.profiles?.display_name||'مستخدم')}</b><p>${esc(x.body||'منشور بصورة')}</p>${x.media_url?`<img class="post-image" src="${esc(x.media_url)}">`:''}<small>${new Date(x.created_at).toLocaleString('ar-EG')}</small></article>`).join('')||'<div class="empty">لا توجد منشورات.</div>'}else if(tab==='reports'){const{data}=await sb.from('reports').select('*').order('created_at',{ascending:false}).limit(80);box.innerHTML=(data||[]).map(x=>`<div class="card comment"><b>🚩 ${esc(x.reason||'بلاغ')}</b><br><small>الحالة: ${esc(x.status||'pending')}</small></div>`).join('')||'<div class="empty">لا توجد بلاغات.</div>'}else{box.innerHTML='<div class="card empty">قسم المجتمع متاح من لوحة الأصدقاء الرئيسية: طلبات الصداقة والاقتراحات والبحث والمراسلة.</div>'}}
  window.MadaAdminInline={open:openAdmin};
  document.addEventListener('DOMContentLoaded',async()=>{const{data:{session}}=await sb.auth.getSession();if(!session)return;const{data:p}=await sb.from('profiles').select('role,is_banned').eq('id',session.user.id).single();if(p?.role==='admin'&&!p.is_banned){const q=document.querySelector('.quick-grid');if(q&&!document.getElementById('adminInlineBtn')){const b=document.createElement('button');b.id='adminInlineBtn';b.innerHTML='<span>⚙️</span>لوحة الإدارة';b.onclick=openAdmin;q.appendChild(b)}}});
})();