/* Mada Admin: Premium dashboard + paid-member reward controls */
(function(){
 const {createClient}=window.supabase; const sb=createClient(window.MADA_SUPABASE_URL,window.MADA_SUPABASE_KEY);
 const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
 const rewards=[
  ['reward_premium_tag','👑 تاج Premium'],['reward_gold_frame','🟨 إطار ذهبي'],['reward_fire','🔥 شارة الحماسة'],
  ['reward_pinned_posts','📌 تثبيت المنشورات'],['reward_advanced_stats','📊 إحصائيات متقدمة'],['reward_exclusive_styles','🎨 ألوان وخلفيات حصرية'],
  ['reward_boost','🚀 Boost'],['reward_edit_posts','✏️ تعديل المنشورات']
 ];
 let realtime=null;
 async function isAdmin(){const {data:{session}}=await sb.auth.getSession();if(!session)return false;const {data:p,error}=await sb.from('profiles').select('role,is_banned').eq('id',session.user.id).maybeSingle();return !error&&p?.role==='admin'&&!p?.is_banned}
 async function count(table,filter){let q=sb.from(table).select('*',{count:'exact',head:true});if(filter)q=q.eq(filter[0],filter[1]);const {count,error}=await q;if(error)throw error;return count||0}
 async function receiptUrl(path){if(!path)return null;if(/^https?:\/\//i.test(path))return path;const {data,error}=await sb.storage.from('payment-receipts').createSignedUrl(path,600);return error?null:data?.signedUrl||null}
 async function render(){
  const c=$('content');if(!c)return;c.innerHTML='<div class="card">جاري تحميل لوحة Premium…</div>';
  try{
   if(!(await isAdmin())){c.innerHTML='<div class="card">غير مصرح بالدخول إلى لوحة Premium.</div>';return}
   const results=await Promise.allSettled([
    sb.from('admin_settings').select('*').eq('id',true).maybeSingle(),
    sb.from('subscription_requests').select('id,user_id,transaction_ref,receipt_image_url,status,created_at').order('created_at',{ascending:false}).limit(100),
    sb.from('profiles').select('id,display_name,username,is_premium,reward_premium_tag,reward_gold_frame,reward_fire,reward_pinned_posts,reward_advanced_stats,reward_exclusive_styles,reward_boost,reward_edit_posts').eq('is_premium',true).order('created_at',{ascending:false}).limit(200),
    count('profiles'),count('posts')
   ]);
   const value=i=>results[i].status==='fulfilled'?results[i].value:null;
   const settingsRes=value(0),requestsRes=value(1),membersRes=value(2);const s=settingsRes?.data||null;const requests=requestsRes?.data||[];const members=membersRes?.data||[];
   const ids=[...new Set(requests.map(x=>x.user_id).filter(Boolean))];let profiles=[];if(ids.length){const pr=await sb.from('profiles').select('id,display_name,username').in('id',ids);profiles=pr.data||[]}
   const pmap=Object.fromEntries(profiles.map(p=>[p.id,p]));const pending=requests.filter(x=>x.status==='pending').length;
   const rows=await Promise.all(requests.map(async x=>({...x,receiptLink:await receiptUrl(x.receipt_image_url)})));
   const premiumUsers=members.length,totalUsers=results[3].status==='fulfilled'?results[3].value:0,posts=results[4].status==='fulfilled'?results[4].value:0;
   c.innerHTML=`<div class="admin-premium-head"><div><h2>💎 Premium</h2><p>إدارة الاشتراكات والدفع والمكافآت</p></div><span class="badge-admin">Mada Admin</span></div>
   <section class="premium-admin-section"><div class="stats-grid"><div class="stat-card"><span class="stat-title">إجمالي المستخدمين</span><h3>${totalUsers}</h3></div><div class="stat-card gold"><span class="stat-title">مشتركو Premium 💎</span><h3>${premiumUsers}</h3></div><div class="stat-card orange"><span class="stat-title">طلبات معلقة ⏳</span><h3>${pending}</h3></div><div class="stat-card"><span class="stat-title">إجمالي المنشورات</span><h3>${posts}</h3></div></div></section>
   <section class="admin-card premium-admin-section"><h3>💳 إعدادات الدفع والاشتراك</h3>${results[0].status==='rejected'?'<div class="notice">تعذر تحميل إعدادات الدفع.</div>':`<div class="form-row"><div class="form-group"><label>رقم المحفظة (Vodafone Cash)</label><input id="premiumWallet" value="${esc(s?.cash_wallet)}" placeholder="010xxxxxxxx"></div><div class="form-group"><label>قيمة الاشتراك الشهري (جنيه)</label><input id="premiumPrice" type="number" min="0" step="0.01" value="${s?.subscription_price_egp??99}"></div></div><button class="btn-primary" id="savePremiumSettings">💾 حفظ التعديلات</button><p id="premiumSaveMsg"></p>`}</section>
   <section class="admin-card premium-admin-section"><div class="section-title-row"><h3>👑 أعضاء Premium المدفوعين — التحكم في المكافآت</h3><span class="pending-chip">${members.length} مشترك</span></div><p class="rewards-help">فعّل أو عطّل أي مكافأة لكل عضو بشكل مستقل. التغيير يُطبّق مباشرة على حساب العضو.</p><div class="rewards-list">${members.map(u=>`<div class="reward-user" data-user="${esc(u.id)}"><div class="reward-user-info"><strong>${esc(u.display_name||u.username||'مستخدم')}</strong><small>${u.username?'@'+esc(u.username)+' · ':''}💎 Premium مدفوع</small></div><div class="reward-checks">${rewards.map(([key,label])=>`<label class="reward-toggle"><input type="checkbox" data-key="${key}" ${u[key]?'checked':''}> ${label}</label>`).join('')}</div><button class="btn-primary reward-save" data-id="${esc(u.id)}">💾 حفظ مكافآت العضو</button></div>`).join('')||'<div class="notice">لا يوجد أعضاء Premium مدفوعون حاليًا.</div>'}</div></section>
   <section class="admin-card premium-admin-section"><div class="section-title-row"><h3>📥 طلبات Premium</h3><span class="pending-chip">${pending} معلقة</span></div>${requestsRes?.error?`<div class="notice">تعذر تحميل طلبات Premium: ${esc(requestsRes.error.message)}</div>`:`<div class="table-responsive"><table class="admin-table"><thead><tr><th>المستخدم</th><th>رقم العملية</th><th>الإيصال</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>${rows.map(x=>{const p=pmap[x.user_id]||{};return `<tr><td><strong>${esc(p.display_name||p.username||'مستخدم')}</strong><small>${esc(p.username?('@'+p.username):'')}</small></td><td>${esc(x.transaction_ref||'-')}</td><td>${x.receiptLink?`<a href="${esc(x.receiptLink)}" target="_blank" rel="noopener" class="view-link">عرض الإيصال 🖼️</a>`:'بدون إيصال'}</td><td><span class="status-${esc(x.status)}">${x.status==='pending'?'معلق':x.status==='approved'?'مقبول':'مرفوض'}</span></td><td>${x.status==='pending'?`<button class="btn-action approve" data-id="${esc(x.id)}">قبول 👑</button><button class="btn-action reject" data-id="${esc(x.id)}">رفض ❌</button>`:'—'}</td></tr>`}).join('')||'<tr><td colspan="5">لا توجد طلبات حتى الآن.</td></tr>'}</tbody></table></div>`}</section>`;
   const save=$('savePremiumSettings');if(save)save.onclick=async()=>{const {data:{session}}=await sb.auth.getSession();const price=Number($('premiumPrice').value);if(!Number.isFinite(price)||price<0)return $('premiumSaveMsg').textContent='اكتب سعراً صحيحاً.';const {error}=await sb.from('admin_settings').update({cash_wallet:$('premiumWallet').value.trim()||null,subscription_price_egp:price,updated_at:new Date().toISOString(),updated_by:session.user.id}).eq('id',true);$('premiumSaveMsg').textContent=error?'تعذر الحفظ: '+error.message:'✅ تم حفظ الإعدادات.'};
   c.querySelectorAll('.reward-save').forEach(btn=>btn.onclick=async()=>{const row=btn.closest('.reward-user'),patch={};row.querySelectorAll('input[data-key]').forEach(i=>patch[i.dataset.key]=i.checked);btn.disabled=true;const {error}=await sb.from('profiles').update(patch).eq('id',btn.dataset.id).eq('is_premium',true);btn.disabled=false;if(error){btn.textContent='❌ تعذر الحفظ';alert('تعذر حفظ المكافآت: '+error.message)}else{btn.textContent='✅ تم حفظ المكافآت';setTimeout(()=>btn.textContent='💾 حفظ مكافآت العضو',1800)}});
   c.querySelectorAll('.approve').forEach(b=>b.onclick=()=>review(b.dataset.id,'approved'));c.querySelectorAll('.reject').forEach(b=>b.onclick=()=>review(b.dataset.id,'rejected'));
  }catch(e){console.error('Premium render failed',e);c.innerHTML=`<div class="card"><h3>تعذر تحميل لوحة Premium</h3><p>${esc(e?.message||e)}</p><button class="btn-primary" onclick="window.madaAdminPremium()">إعادة المحاولة</button></div>`}
 }
 async function review(id,status){if(!(await isAdmin()))return alert('غير مصرح');if(status==='rejected'&&!confirm('تأكيد رفض طلب Premium؟'))return;if(status==='approved'){const {error}=await sb.rpc('approve_subscription_request',{p_request_id:id});if(error)return alert('تعذر تأكيد الدفع: '+error.message);alert('تم تأكيد الدفع وتفعيل Premium ✓')}else{const {data:{session}}=await sb.auth.getSession();const {error}=await sb.from('subscription_requests').update({status:'rejected',reviewed_at:new Date().toISOString(),reviewed_by:session?.user?.id||null}).eq('id',id).eq('status','pending');if(error)return alert('تعذر رفض الطلب: '+error.message)}render()}
 function startRealtime(){if(realtime)return;realtime=sb.channel('mada-premium-requests').on('postgres_changes',{event:'*',schema:'public',table:'subscription_requests'},()=>{if(document.querySelector('#dash:not([hidden])')&&document.querySelector('#content'))render()}).subscribe()}
 window.madaAdminPremium=render;document.addEventListener('DOMContentLoaded',()=>{const b=document.querySelector('#dash aside button[data-tab="premium"]');if(b)b.onclick=render;startRealtime()});
})();