/* Mada: minimal, non-blocking authentication. No observers, timers, or startup loops. */
(function(){
  const $=id=>document.getElementById(id);
  const sb=()=>window.MADA_SUPABASE_CLIENT||window.sb;
  const auth=()=>$('auth');
  const card=()=>document.querySelector('#auth .auth-card');
  function msg(text,ok){const x=$('authMsg');if(!x)return;x.textContent=text||'';x.style.display='block';x.style.color=ok?'#16803c':'#c62828'}
  function close(){const a=auth();if(!a)return;a.hidden=true;a.style.display='none';document.body.classList.remove('auth-sheet-open')}
  function open(){const a=auth();if(!a)return;a.hidden=false;a.style.display='flex';document.body.classList.add('auth-sheet-open')}
  function closeButton(){const b=document.querySelector('#auth .auth-sheet-close');if(b)b.onclick=close}
  function loginView(){const c=card();if(!c)return;c.innerHTML='<button class="auth-sheet-close" type="button" aria-label="إغلاق">×</button><div class="mada-logo large"><span class="logo-mark">M</span><div>MADA</div><small>مدى</small></div><p>تواصل .. شارك .. اكتشف</p><input id="nameInput" type="text" placeholder="الاسم الكامل (اختياري)" autocomplete="name"><input id="emailInput" type="text" placeholder="البريد الإلكتروني أو رقم الهاتف" autocomplete="username"><input id="passwordInput" type="password" placeholder="كلمة المرور" autocomplete="current-password"><button id="loginBtn" class="primary wide" type="button">تسجيل الدخول</button><button id="signupBtn" class="auth-secondary wide" type="button">إنشاء حساب جديد</button><button id="forgotBtn" class="link-btn" type="button">نسيت كلمة السر؟</button><button id="adminLoginBtn" class="admin-action" type="button">⚙️ دخول الإدارة</button><div id="authMsg" class="muted"></div>';closeButton();$('loginBtn').onclick=login;$('signupBtn').onclick=signupView;$('forgotBtn').onclick=forgot;$('adminLoginBtn').onclick=()=>location.href='admin.html'}
  function signupView(){const c=card();if(!c)return;c.innerHTML='<button class="auth-sheet-close" type="button" aria-label="إغلاق">×</button><div class="mada-logo"><div style="font-size:32px;color:#2574df;font-weight:900">MADA</div><small style="color:#17a2e8;font-size:20px">إنشاء حساب جديد</small></div><p>أنشئ حسابك في مدى</p><input id="signupName" type="text" placeholder="الاسم الكامل" autocomplete="name"><input id="signupEmail" type="email" placeholder="البريد الإلكتروني" autocomplete="email"><input id="signupPassword" type="password" placeholder="كلمة المرور (6 أحرف على الأقل)" autocomplete="new-password"><button id="signupSubmit" class="primary wide" type="button">إنشاء الحساب</button><button id="backLogin" class="link-btn" type="button">العودة لتسجيل الدخول</button><div id="authMsg" class="muted"></div>';closeButton();$('signupSubmit').onclick=signup;$('backLogin').onclick=loginView}
  async function login(){const s=sb(),id=$('emailInput')?.value.trim(),password=$('passwordInput')?.value||'';if(!s?.auth)return msg('الخدمة غير متاحة الآن.');if(!id||!password)return msg('اكتب البريد الإلكتروني ورقم الهاتف وكلمة المرور.');if(!id.includes('@')&&!/^\+?[0-9][0-9\s-]{7,}$/.test(id))return msg('اكتب بريدًا إلكترونيًا أو رقم هاتف صحيحًا.');const b=$('loginBtn');if(b){b.disabled=true;b.textContent='جاري الدخول…'}try{const r=await s.auth.signInWithPassword(id.includes('@')?{email:id,password}:{phone:id.replace(/[\s-]/g,''),password});if(r.error){msg(r.error.message);return}close();const app=$('app');if(app)app.hidden=false}catch(e){msg('تعذر تسجيل الدخول: '+(e?.message||e))}finally{const x=$('loginBtn');if(x){x.disabled=false;x.textContent='تسجيل الدخول'}}}
  async function signup(){const s=sb(),name=$('signupName')?.value.trim(),email=$('signupEmail')?.value.trim(),password=$('signupPassword')?.value||'';if(!s?.auth)return msg('الخدمة غير متاحة الآن.');if(!name||!email||!password)return msg('اكتب الاسم والبريد الإلكتروني وكلمة المرور.');if(password.length<6)return msg('كلمة المرور يجب أن تكون 6 أحرف على الأقل.');const b=$('signupSubmit');if(b){b.disabled=true;b.textContent='جاري إنشاء الحساب…'}try{const r=await s.auth.signUp({email,password,options:{data:{display_name:name,username:email.split('@')[0]}}});if(r.error){msg(r.error.message);return}if(r.data?.session){close();const app=$('app');if(app)app.hidden=false}else msg('تم إنشاء الحساب. افتح رسالة التأكيد في بريدك الإلكتروني ثم سجّل الدخول.',true)}catch(e){msg('تعذر إنشاء الحساب: '+(e?.message||e))}finally{const x=$('signupSubmit');if(x){x.disabled=false;x.textContent='إنشاء الحساب'}}}
  async function forgot(){const s=sb(),email=$('emailInput')?.value.trim();if(!s?.auth)return msg('الخدمة غير متاحة الآن.');if(!email||!email.includes('@'))return msg('اكتب بريدك الإلكتروني أولًا.');try{const r=await s.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(r.error){msg(r.error.message);return}msg('تم إرسال رابط إعادة تعيين كلمة السر إلى بريدك الإلكتروني ✓',true)}catch(e){msg('تعذر إرسال الرابط: '+(e?.message||e))}}
  async function boot(){const s=sb();if(!auth())return;const r=await s?.auth?.getSession?.();if(r?.data?.session){close();const app=$('app');if(app)app.hidden=false}else{open();loginView()}s?.auth?.onAuthStateChange?.((event,session)=>{if(session){close();const app=$('app');if(app)app.hidden=false}else if(event==='SIGNED_OUT'){open();loginView()}})}
  window.MadaAuth={open,close,loginView,signupView,forgot};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
