/* Mada comments menu v2 — reliable menu, sorting and refresh controls. */
(()=>{'use strict';
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const close=()=>{const m=q('#commentsMenu'),b=q('#commentsMenuBtn');if(m)m.hidden=true;if(b)b.setAttribute('aria-expanded','false')};
const open=()=>{const m=q('#commentsMenu'),b=q('#commentsMenuBtn');if(m)m.hidden=false;if(b)b.setAttribute('aria-expanded','true')};
const toast=t=>{const e=q('#toast');if(!e)return;e.textContent=t;e.hidden=false;clearTimeout(window.__madaMenuToast);window.__madaMenuToast=setTimeout(()=>e.hidden=true,1800)};
function apply(mode){const list=q('#commentsList');if(!list)return;const rows=qa('#commentsList>.comment');if(rows.length>1){const frag=document.createDocumentFragment();(mode==='old'?rows.reverse():rows).forEach(x=>frag.appendChild(x));list.appendChild(frag)}localStorage.setItem('mada-comments-sort',mode);const s=q('#sortBtn');if(s){s.textContent=mode==='old'?'الأقدم أولاً⌄':'الأحدث أولاً⌄';s.setAttribute('aria-label',s.textContent)}qa('[data-menu-sort]').forEach(x=>x.classList.toggle('selected',x.dataset.menuSort===mode));close()}
function bind(){const b=q('#commentsMenuBtn'),m=q('#commentsMenu'),s=q('#sortBtn');if(!b||!m)return;b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();m.hidden?open():close()});b.addEventListener('pointerup',e=>e.stopPropagation());document.addEventListener('click',e=>{const target=e.target;if(m&&!m.hidden&&!target.closest('#commentsMenu')&&!target.closest('#commentsMenuBtn'))close();const sort=target.closest('[data-menu-sort]');if(sort){e.preventDefault();e.stopPropagation();apply(sort.dataset.menuSort==='old'?'old':'new');return}if(target.closest('[data-menu-refresh]')){e.preventDefault();close();location.reload();return}const sb=target.closest('#sortBtn');if(sb){e.preventDefault();apply((localStorage.getItem('mada-comments-sort')||'new')==='new'?'old':'new')}});if(s)s.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();apply((localStorage.getItem('mada-comments-sort')||'new')==='new'?'old':'new')});window.setTimeout(()=>apply(localStorage.getItem('mada-comments-sort')||'new'),1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();