/* Mada dedicated comments page v2 — lightweight, paginated, RTL, schema-tolerant. */
(function(){
'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const postId=new URLSearchParams(location.search).get('post'),PAGE=30;let client,user,offset=0,loading=false;
const uid=o=>o?.user_id||o?.author_id||o?.profile_id||null,txt=o=>o?.body??o?.content??o?.text??'',media=o=>o?.image_url||o?.media_url||o?.image||null,name=p=>p?.display_name||p?.name||p?.username||'مستخدم',initial=n=>(String(n||'م').trim()[0]||'م').toUpperCase();
function dt(v){try{return new Date(v).toLocaleString('ar-EG',{day:'numeric',month:'long',year:'numeric',hour:'numeric',minute:'2-digit'})}catch{return ''}}
function toast(x){const t=$('toast');t.textContent=x;t.hidden=false;clearTimeout(window.madaToast);window.madaToast=setTimeout(()=>t.hidden=true,2500)}
async function getProfiles(ids){if(!ids.length)return new Map();const r=await client.from('profiles').select('id,display_name,username,avatar_url').in('id',ids);return new Map((r.data||[]).map(p=>[p.id,p]))}
async function loadPost(){if(!postId){$('postCard').innerHTML='<div class="empty">المنشور غير موجود.</div>';return false}const r=await client.from('posts').select('*').eq('id',postId).maybeSingle();if(r.error||!r.data){$('postCard').innerHTML='<div class="empty">تعذر تحميل المنشور.</div>';return false}const p=r.data,id=uid(p);let prof=null;if(id){const q=await client.from('profiles').select('id,display_name,username,avatar_url').eq('id',id).maybeSingle();prof=q.data||null}const n=name(prof);$('postCard').innerHTML=`<div class="post-author"><div class="avatar">${esc(initial(n))}</div><div class="author-info"><strong>${esc(n)}</strong><time>${esc(dt(p.created_at))}</time></div><button class="post-more" type="button">•••</button></div><div class="post-text">${esc(txt(p))}</div>${media(p)?`<img class="post-media" src="${esc(media(p))}" alt="" loading="lazy">`:''}`;return true}
async function count(){const r=await client.from('comments').select('*',{count:'exact',head:true}).eq('post_id',postId);if(!r.error){$('commentsCount').textContent=String(r.count||0);$('commentsSubtitle').textContent=`${r.count||0} تعليق`}}
function row(c,p){const n=name(p);return `<article class="comment-row" data-id="${esc(c.id)}"><div class="avatar small">${esc(initial(n))}</div><div class="comment-main"><div class="comment-author"><strong>${esc(n)}</strong><time>${esc(dt(c.created_at))}</time></div><div class="comment-text">${esc(txt(c))}</div><div class="comment-actions"><button type="button">♡ 0</button><button type="button">↩ رد</button>${user&&uid(c)===user.id?`<button type="button" data-delete="${esc(c.id)}">🗑 حذف</button>`:''}</div></div></article>`}
async function loadMore(reset){if(loading)return;loading=true;const list=$('commentsList'),more=$('loadMoreBtn');if(reset){offset=0;list.innerHTML='<div class="loading">جاري تحميل التعليقات…</div>';more.hidden=true}const r=await client.from('comments').select('*').eq('post_id',postId).order('created_at',{ascending:false}).range(offset,offset+PAGE-1);if(r.error){if(reset)list.innerHTML='<div class="empty">تعذر تحميل التعليقات.</div>';toast('تعذر تحميل التعليقات');loading=false;return}const rows=r.data||[],ps=await getProfiles([...new Set(rows.map(uid).filter(Boolean))]);if(reset)list.innerHTML='';if(reset&&!rows.length)list.innerHTML='<div class="empty">لا توجد تعليقات بعد 👋</div>';rows.forEach(c=>list.insertAdjacentHTML('beforeend',row(c,ps.get(uid(c)))));offset+=rows.length;more.hidden=rows.length<PAGE;await count();loading=false}
async function send(e){e.preventDefault();if(!user){toast('سجّل الدخول لكتابة تعليق');return}const input=$('commentInput'),btn=$('sendBtn'),body=input.value.trim();if(!body)return;input.disabled=btn.disabled=true;btn.textContent='جارٍ…';let r=await client.from('comments').insert({post_id:postId,author_id:user.id,body}).select('*').single();if(r.error)r=await client.from('comments').insert({post_id:postId,user_id:user.id,body}).select('*').single();input.disabled=btn.disabled=false;btn.textContent='إرسال';if(r.error){toast('تعذر إضافة التعليق');return}input.value='';$('commentsList').querySelector('.empty')?.remove();$('commentsList').insertAdjacentHTML('afterbegin',row(r.data,{display_name:'أنت'}));await count()}
function back(){if(history.length>1)history.back();else location.href='index.html'}
async function boot(){$('backBtn').onclick=back;$('loadMoreBtn').onclick=()=>loadMore(false);$('commentForm').onsubmit=send;client=window.MADA_SUPABASE_CLIENT||window.sb||window.supabase?.createClient?.(window.MADA_SUPABASE_URL,window.MADA_SUPABASE_KEY);if(!client){$('postCard').innerHTML='<div class="empty">تعذر تشغيل صفحة التعليقات.</div>';return}const s=await client.auth.getSession();user=s.data?.session?.user||null;if(!user){$('commentInput').disabled=true;$('sendBtn').disabled=true;$('commentInput').placeholder='سجّل الدخول لكتابة تعليق'}if(await loadPost())await loadMore(true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();