/* Mada Comments Modern v2 — reply, delete, live refresh */
(function(){
  const get=id=>document.getElementById(id);
  const db=()=>typeof sb!=='undefined'?sb:null;
  const me=()=>typeof user!=='undefined'?user:null;
  let replyTarget=null;
  function toast(msg){if(typeof window.showToast==='function')return window.showToast(msg);let t=get('madaCommentToast');if(!t){t=document.createElement('div');t.id='madaCommentToast';t.className='mada-comment-toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2200)}
  function ensureReplyBar(){if(get('commentReplyBar'))return;const bar=document.createElement('div');bar.id='commentReplyBar';bar.className='comment-reply-bar';bar.hidden=true;bar.innerHTML='<span>↩️ الرد على <b id="commentReplyName"></b></span><button type="button" id="cancelCommentReply">×</button>';document.body.appendChild(bar);get('cancelCommentReply').onclick=()=>{replyTarget=null;bar.hidden=true}}
  function startReply(c){ensureReplyBar();replyTarget={id:c.dataset.commentId,name:c.dataset.authorName||'مستخدم'};get('commentReplyName').textContent=replyTarget.name;get('commentReplyBar').hidden=false;const input=c.closest('.post')?.querySelector('.comment-box input');if(input){input.placeholder='اكتب ردك...';input.focus()}}
  async function deleteComment(c){const d=db(),u=me(),id=c?.dataset.commentId;if(!d||!u||!id)return;if(!confirm('حذف هذا التعليق؟'))return;const{error}=await d.from('comments').delete().eq('id',id).eq('author_id',u.id);if(error){console.error(error);toast('تعذر حذف التعليق');return}c.remove();toast('تم حذف التعليق')}
  function decorate(){document.querySelectorAll('#feed .comment').forEach(c=>{if(c.dataset.enhanced)return;c.dataset.enhanced='1';const first=c.querySelector('b');const name=first?.textContent||'مستخدم';const raw=first?c.textContent.trim().slice(name.length).trim():c.textContent.trim();c.dataset.authorName=name;const body=document.createElement('span');body.className='comment-body';const b=document.createElement('b');b.textContent=name;body.appendChild(b);const txt=document.createElement('span');txt.textContent=raw;body.appendChild(txt);const tools=document.createElement('span');tools.className='comment-tools';const reply=document.createElement('button');reply.type='button';reply.textContent='رد';reply.onclick=e=>{e.stopPropagation();startReply(c)};tools.appendChild(reply);c.replaceChildren(body,tools)})}
  async function addTools(){decorate();const d=db(),u=me();if(!d||!u)return;const comments=[...document.querySelectorAll('#feed .comment')];const postIds=[...new Set(comments.map(c=>c.closest('.post')?.dataset.postId).filter(Boolean))];for(const pid of postIds){const{data}=await d.from('comments').select('id,author_id,body,created_at').eq('post_id',pid).order('created_at',{ascending:true});const rows=data||[];comments.filter(c=>c.closest('.post')?.dataset.postId===pid).forEach((c,i)=>{const row=rows[i];if(!row)return;c.dataset.commentId=row.id;c.dataset.authorName=c.querySelector('b')?.textContent||'مستخدم';if(row.author_id===u.id&&!c.querySelector('.comment-delete')){const btn=document.createElement('button');btn.type='button';btn.className='comment-delete';btn.textContent='حذف';btn.onclick=e=>{e.stopPropagation();deleteComment(c)};c.querySelector('.comment-tools')?.appendChild(btn)}})}}
  const original=typeof window.addComment==='function'?window.addComment:null;
  window.addComment=async function(postId){const d=db(),u=me();if(!d||!u)return original?original(postId):null;const box=document.querySelector(`#feed [data-comment="${CSS.escape(postId)}"]`),text=box?.value.trim();if(!text)return;const send=document.querySelector(`#feed [data-send="${CSS.escape(postId)}"]`);if(send){send.disabled=true;send.dataset.oldText=send.textContent;send.textContent='…'}try{const body=replyTarget?`↩️ @${replyTarget.name} ${text}`:text;const{error}=await d.from('comments').insert({post_id:postId,author_id:u.id,body});if(error)throw error;box.value='';box.placeholder='اكتب تعليقًا...';replyTarget=null;if(get('commentReplyBar'))get('commentReplyBar').hidden=true;if(typeof loadFeed==='function')await loadFeed();toast('تم نشر التعليق ✓')}catch(err){console.error(err);toast('تعذر إضافة التعليق')}finally{if(send){send.disabled=false;send.textContent=send.dataset.oldText||'إرسال'}}};
  const observer=new MutationObserver(()=>{clearTimeout(window.__commentEnhanceTimer);window.__commentEnhanceTimer=setTimeout(addTools,120)});
  function init(){ensureReplyBar();const feed=get('feed');if(feed)observer.observe(feed,{childList:true,subtree:true});setTimeout(addTools,700)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
