/* Mada Comments Modern v5 — reliable session recovery, comments, replies, delete, realtime and duplicate guard. */
(function(){
  const get=id=>document.getElementById(id), db=()=>window.sb||null, me=()=>window.user||null;
  const pending=new Set(); let replyTarget=null,realtime=null;
  function toast(msg){if(window.showToast)return window.showToast(msg);let t=get('madaCommentToast');if(!t){t=document.createElement('div');t.id='madaCommentToast';t.className='mada-comment-toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2200)}
  function findPost(id){return document.querySelector(`article.post[data-post-id="${CSS.escape(id)}"]`)}
  function ensureReplyBar(){if(get('commentReplyBar'))return;const b=document.createElement('div');b.id='commentReplyBar';b.className='comment-reply-bar';b.hidden=true;b.innerHTML='<span>↩️ الرد على <b id="commentReplyName"></b></span><button type="button" id="cancelCommentReply">×</button>';document.body.appendChild(b);get('cancelCommentReply').onclick=clearReply}
  function clearReply(){replyTarget=null;const b=get('commentReplyBar');if(b)b.hidden=true;document.querySelectorAll('.comment-box input').forEach(i=>i.placeholder='اكتب تعليقًا...')}
  function startReply(c){ensureReplyBar();replyTarget={id:c.dataset.commentId,name:c.dataset.authorName||'مستخدم',postId:c.closest('.post')?.dataset.postId};get('commentReplyName').textContent=replyTarget.name;get('commentReplyBar').hidden=false;const i=c.closest('.post')?.querySelector('.comment-box input');if(i){i.placeholder=`الرد على ${replyTarget.name}...`;i.focus()}}
  function commentsHost(p){return p?.querySelector('.comments')||p?.querySelector('.comments-list')||p?.querySelector('.post-comments')||null}
  async function activeUser(){const d=db();if(!d)return null;if(window.user?.id)return window.user;try{const{data,error}=await d.auth.getSession();if(error)throw error;const u=data?.session?.user;if(u){window.user=u;return u}}catch(e){console.warn('Mada comment auth recovery',e)}return null}
  async function deleteComment(c){const d=db(),u=await activeUser(),id=c?.dataset.commentId,key='del:'+id;if(!d||!u||!id||pending.has(key))return;if(!confirm('حذف هذا التعليق؟'))return;pending.add(key);const btn=c.querySelector('.comment-delete');if(btn)btn.disabled=true;try{const{error}=await d.from('comments').delete().eq('id',id).eq('author_id',u.id);if(error)throw error;c.remove();window.madaRefreshPostStats?.(c.closest('.post')?.dataset.postId);toast('تم حذف التعليق ✓')}catch(e){toast('تعذر حذف التعليق: '+(e?.message||'خطأ غير معروف'))}finally{pending.delete(key);if(btn)btn.disabled=false}}
  function decorate(){document.querySelectorAll('#feed .comment').forEach(c=>{if(c.dataset.enhanced)return;c.dataset.enhanced='1';const first=c.querySelector('b'),name=first?.textContent||'مستخدم';const raw=first?c.textContent.trim().slice(name.length).trim():c.textContent.trim();c.dataset.authorName=name;const body=document.createElement('span');body.className='comment-body';const b=document.createElement('b');b.textContent=name;const txt=document.createElement('span');txt.textContent=raw;body.append(b,txt);const tools=document.createElement('span');tools.className='comment-tools';const r=document.createElement('button');r.type='button';r.textContent='رد';r.onclick=e=>{e.stopPropagation();startReply(c)};tools.appendChild(r);c.replaceChildren(body,tools)})}
  async function addTools(){decorate();const d=db(),u=await activeUser();if(!d||!u)return;const cs=[...document.querySelectorAll('#feed .comment')],pids=[...new Set(cs.map(c=>c.closest('.post')?.dataset.postId).filter(Boolean))];for(const pid of pids){const{data}=await d.from('comments').select('id,author_id,parent_id').eq('post_id',pid).order('created_at',{ascending:true});(data||[]).forEach((row,i)=>{const c=cs.filter(x=>x.closest('.post')?.dataset.postId===pid)[i];if(!c)return;c.dataset.commentId=row.id;c.dataset.parentId=row.parent_id||'';if(row.author_id===u.id&&!c.querySelector('.comment-delete')){const x=document.createElement('button');x.type='button';x.className='comment-delete';x.textContent='حذف';x.onclick=e=>{e.stopPropagation();deleteComment(c)};c.querySelector('.comment-tools')?.appendChild(x)}})}}
  function appendLocal(pid,row,u){const host=commentsHost(findPost(pid));if(!host||!row)return;const c=document.createElement('div');c.className='comment mada-live-comment';c.dataset.commentId=row.id;c.dataset.parentId=row.parent_id||'';c.dataset.authorName=u.display_name||u.email||'أنت';const body=document.createElement('span');body.className='comment-body';const b=document.createElement('b');b.textContent=c.dataset.authorName;const txt=document.createElement('span');txt.textContent=row.body||'';body.append(b,txt);const tools=document.createElement('span');tools.className='comment-tools';const reply=document.createElement('button');reply.type='button';reply.textContent='رد';reply.onclick=e=>{e.stopPropagation();startReply(c)};tools.appendChild(reply);const del=document.createElement('button');del.type='button';del.className='comment-delete';del.textContent='حذف';del.onclick=e=>{e.stopPropagation();deleteComment(c)};tools.appendChild(del);c.append(body,tools);if(row.parent_id){const parent=host.querySelector(`[data-comment-id="${CSS.escape(row.parent_id)}"]`);if(parent)parent.insertAdjacentElement('afterend',c);else host.appendChild(c)}else host.appendChild(c)}
  async function addComment(postId){const d=db(),u=await activeUser(),key='add:'+postId;if(!d||!u||!postId||pending.has(key)){if(!u)toast('تأكد أن الحساب مسجل الدخول');return}const box=document.querySelector(`#feed [data-comment="${CSS.escape(postId)}"]`),text=box?.value.trim();if(!text)return;const send=document.querySelector(`#feed [data-send="${CSS.escape(postId)}"]`);pending.add(key);if(send){send.disabled=true;send.textContent='…'}try{const parentId=replyTarget&&replyTarget.postId===postId?replyTarget.id:null;const{data,error}=await d.from('comments').insert({post_id:postId,author_id:u.id,body:text,parent_id:parentId}).select('id,post_id,author_id,body,parent_id,created_at').single();if(error)throw error;if(box)box.value='';clearReply();appendLocal(postId,data,{display_name:window.profile?.display_name||u.email||'أنت'});window.madaRefreshPostStats?.(postId);toast(parentId?'تم نشر الرد ✓':'تم نشر التعليق ✓')}catch(e){console.error('Mada comment send failed',e);toast('تعذر إضافة التعليق: '+(e?.message||'حدث خطأ'))}finally{pending.delete(key);if(send){send.disabled=false;send.textContent='إرسال'}}}
  function startRealtime(){const d=db(),u=me();if(!d||!u||realtime)return;realtime=d.channel('mada-comments-'+u.id).on('postgres_changes',{event:'INSERT',schema:'public',table:'comments'},p=>{const r=p.new;if(!r?.post_id)return;window.madaRefreshPostStats?.(r.post_id);if(r.author_id!==u.id){const post=findPost(r.post_id);if(post&&commentsHost(post)&&!commentsHost(post).querySelector(`[data-comment-id="${CSS.escape(r.id)}"]`)){appendRemote(r);toast('تعليق جديد 💬')}}}).on('postgres_changes',{event:'DELETE',schema:'public',table:'comments'},p=>{const id=p.old?.id;if(id)document.querySelector(`[data-comment-id="${CSS.escape(id)}"]`)?.remove();if(p.old?.post_id)window.madaRefreshPostStats?.(p.old.post_id)}).subscribe()}
  async function appendRemote(r){const d=db();let u={display_name:'مستخدم Mada'};if(d&&r.author_id){const{data}=await d.from('profiles').select('display_name').eq('id',r.author_id).maybeSingle();u=data||u}appendLocal(r.post_id,r,u)}
  const observer=new MutationObserver(()=>{clearTimeout(window.__commentEnhanceTimer);window.__commentEnhanceTimer=setTimeout(addTools,120)});
  function init(){ensureReplyBar();const feed=get('feed');if(feed)observer.observe(feed,{childList:true,subtree:true});setTimeout(addTools,700);setTimeout(startRealtime,1800)}
  window.addComment=addComment;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
