/* Mada comments menu v3 — sorting, refresh and post likers. */
(()=>{'use strict';
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const close=()=>{const m=q('#commentsMenu'),b=q('#commentsMenuBtn');if(m)m.hidden=true;if(b)b.setAttribute('aria-expanded','false')};
const open=()=>{const m=q('#commentsMenu'),b=q('#commentsMenuBtn');if(m)m.hidden=false;if(b)b.setAttribute('aria-expanded','true')};
const toast=t=>{const e=q('#toast');if(!e)return;e.textContent=t;e.hidden=false;clearTimeout(window.__madaMenuToast);window.__madaMenuToast=setTimeout(()=>e.hidden=true,1800)};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const initial=n=>(String(n||'م').trim()[0]||'م').toUpperCase();
function apply(mode){const list=q('#commentsList');if(!list)return;const rows=qa('#commentsList>.comment');if(rows.length>1){const frag=document.createDocumentFragment();(mode==='old'?rows.reverse():rows).forEach(x=>frag.appendChild(x));list.appendChild(frag)}localStorage.setItem('mada-comments-sort',mode);const s=q('#sortBtn');if(s){s.textContent=mode==='old'?'الأقدم أولاً⌄':'الأحدث أولاً⌄';s.setAttribute('aria-label',s.textContent)}qa('[data-menu-sort]').forEach(x=>x.classList.toggle('selected',x.dataset.menuSort===mode));close()}
async function postLikers(){const sb=window.MADA_SUPABASE_CLIENT||window.sb,postId=new URLSearchParams(location.search).get('post');if(!sb||!postId){toast('المنشور غير صالح');return}const r=await sb.from('post_likes').select('user_id,reaction_type,created_at').eq('post_id',postId).order('created_at',{ascending:false}).limit(100);if(r.error){toast('تعذر تحميل أعضاء الإعجاب');return}const ids=[...new Set((r.data||[]).map(x=>x.user_id).filter(Boolean))];const ps=ids.length?(await sb.from('profiles').select('id,display_name,username,avatar_url,is_verified').in('id',ids)).data||[]:[],pm=new Map(ps.map(x=>[x.id,x]));const name=p=>p?.display_name||p?.name||p?.username||'مستخدم';const av=p=>p?.avatar_url?`<img class="avatar" src="${esc(p.avatar_url)}" alt="" loading="lazy">`:`<span class="avatar">${esc(initial(name(p)))}</span>`;const list=q('#likersList'),title=q('#likersTitle');if(!r.data?.length){toast('لا توجد إعجابات على هذا المنشور بعد');return}if(title)title.textContent=`المعجبون بالمنشور (${r.data.length})`;if(list)list.innerHTML=r.data.map(x=>{const p=pm.get(x.user_id)||{};return `<div class="liker">${av(p)}<strong>${esc(name(p))}</strong><span>${x.reaction_type==='love'?'❤️':x.reaction_type==='haha'?'😂':x.reaction_type==='wow'?'😮':x.reaction_type==='sad'?'😢':x.reaction_type==='angry'?'😡':'👍'}</span></div>`}).join('');const modal=q('#likersModal');if(modal)modal.hidden=false;close()}
function ensureLikersButton(){const m=q('#commentsMenu');if(!m||m.querySelector('[data-menu-likers]'))return;const b=document.createElement('button');b.type='button';b.dataset.menuLikers='1';b.textContent='👥 الأعضاء الذين أعجبوا بالمنشور';m.insertBefore(b,m.firstChild)}
function bind(){const b=q('#commentsMenuBtn'),m=q('#commentsMenu'),s=q('#sortBtn');if(!b||!m)return;ensureLikersButton();b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();m.hidden?open():close()});b.addEventListener('pointerup',e=>e.stopPropagation());document.addEventListener('click',e=>{const target=e.target;if(m&&!m.hidden&&!target.closest('#commentsMenu')&&!target.closest('#commentsMenuBtn'))close();const sort=target.closest('[data-menu-sort]');if(sort){e.preventDefault();e.stopPropagation();apply(sort.dataset.menuSort==='old'?'old':'new');return}if(target.closest('[data-menu-likers]')){e.preventDefault();e.stopPropagation();postLikers();return}if(target.closest('[data-menu-refresh]')){e.preventDefault();close();location.reload();return}const sb=target.closest('#sortBtn');if(sb){e.preventDefault();apply((localStorage.getItem('mada-comments-sort')||'new')==='new'?'old':'new')}});if(s)s.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();apply((localStorage.getItem('mada-comments-sort')||'new')==='new'?'old':'new')});window.setTimeout(()=>apply(localStorage.getItem('mada-comments-sort')||'new'),1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();