/* Mada group unread + notification deep link */
(function(){
 const S=()=>{try{return sb}catch(e){return window.sb||null}}; const U=()=>{try{return user}catch(e){return window.user||null}};
 const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
 async function mark(cid){const s=S();if(!s||!cid)return;try{await s.rpc('mark_conversation_read',{p_conversation_id:cid})}catch(e){} }
 async function unread(cid){const s=S(),u=U();if(!s||!u)return 0;const r=await s.from('conversation_reads').select('last_read_at').eq('conversation_id',cid).eq('user_id',u.id).maybeSingle();const since=r.data?.last_read_at||'1970-01-01T00:00:00Z';const q=await s.from('messages').select('id',{count:'exact',head:true}).eq('conversation_id',cid).neq('sender_id',u.id).gt('created_at',since);return q.count||0}
 async function refresh(){const s=S(),u=U();if(!s||!u)return;const mem=await s.from('conversation_members').select('conversation_id').eq('user_id',u.id).limit(100);for(const x of mem.data||[]){const g=await s.from('group_conversations').select('group_id').eq('conversation_id',x.conversation_id).maybeSingle();if(!g.data)continue;const n=await unread(x.conversation_id);const row=document.querySelector('.mm-row[data-cid="'+CSS.escape(x.conversation_id)+'"]');if(row){let b=row.querySelector('.gm-group-unread');if(n){if(!b){b=document.createElement('span');b.className='gm-group-unread';row.style.position='relative';row.appendChild(b)}b.textContent=n>99?'99+':n}else b?.remove()}}}
 window.openMadaConversation=async function(cid){if(!cid)return;window.__madaPendingConversationId=String(cid);if(typeof window.madaMessenger==='function')window.madaMessenger();let tries=0;const go=()=>{tries++;const row=document.querySelector('.mm-row[data-cid="'+CSS.escape(String(cid))+'"]');if(row){row.click();setTimeout(()=>mark(cid),250);return}if(tries<30)setTimeout(go,250);};setTimeout(go,250)};
 document.addEventListener('click',e=>{const row=e.target.closest('.mm-row[data-cid]');if(row&&window.__madaGroupConversation?.conversationId===row.dataset.cid)setTimeout(()=>mark(row.dataset.cid),300)});
 setInterval(refresh,5000);document.addEventListener('DOMContentLoaded',()=>setTimeout(refresh,1800));
 const st=document.createElement('style');st.textContent='.gm-group-unread{position:absolute;top:8px;left:10px;min-width:20px;height:20px;padding:0 6px;border-radius:99px;background:#e53935;color:#fff;font:800 11px/20px sans-serif;text-align:center;box-shadow:0 2px 8px #0003;z-index:3}.mm-row{position:relative}';document.head.appendChild(st);
})();