/* Mada Groups - banned members management */
(function(){
 const S=()=>{try{return sb}catch(e){return window.sb||null}};
 const U=()=>{try{return user}catch(e){return window.user||null}};
 const toast=m=>window.madaToast?window.madaToast(m):window.showToast?window.showToast(m):console.log(m);
 const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
 async function openBans(gid){const s=S(),u=U();if(!s||!u)return;const g=await s.from('groups').select('owner_id').eq('id',gid).maybeSingle();const m=await s.from('group_members').select('role').eq('group_id',gid).eq('user_id',u.id).maybeSingle();if(g.data?.owner_id!==u.id&&!['admin','owner'].includes(m.data?.role)){toast('هذه الصفحة للمشرفين فقط');return}const b=await s.from('group_bans').select('user_id,reason,created_at').eq('group_id',gid).order('created_at',{ascending:false});if(b.error){toast('تعذر تحميل المحظورين');return}const ids=(b.data||[]).map(x=>x.user_id);const p=ids.length?await s.from('profiles').select('id,display_name,username,avatar_url').in('id',ids):{data:[]};const pm=new Map((p.data||[]).map(x=>[x.id,x]));const old=document.getElementById('madaBansOverlay');old?.remove();const o=document.createElement('div');o.id='madaBansOverlay';o.className='gm-ban-overlay';o.innerHTML='<div class="gm-ban-card"><div class="gm-ban-head"><b>🚫 المحظورون</b><button id="gmBanClose">✕</button></div><div class="gm-ban-list">'+((b.data||[]).map(x=>{const q=pm.get(x.user_id)||{};return '<div class="gm-ban-row"><span class="gm-ban-avatar">'+(q.avatar_url?'<img src="'+esc(q.avatar_url)+'">':'🚫')+'</span><span><b>'+esc(q.display_name||'مستخدم Mada')+'</b><small>@'+esc(q.username||'')+'</small><em>'+esc(x.reason||'بدون سبب')+'</em></span><button data-unban="'+esc(x.user_id)+'">فك الحظر</button></div>'}).join('')||'<div class="gm-ban-empty">لا يوجد أعضاء محظورون 🎉</div>')+'</div></div>';document.body.appendChild(o);o.onclick=e=>{if(e.target===o)o.remove()};o.querySelector('#gmBanClose').onclick=()=>o.remove();o.querySelectorAll('[data-unban]').forEach(btn=>btn.onclick=async()=>{btn.disabled=true;const z=await s.rpc('group_admin_unban_member',{p_group_id:gid,p_user_id:btn.dataset.unban});if(z.error){toast('تعذر فك الحظر');btn.disabled=false}else{toast('تم فك الحظر ✅');openBans(gid)}})}
 function inject(){const meta=window.__madaGroupConversation;if(!meta?.groupId)return;const head=document.getElementById('mmChatHeader')||document.querySelector('.mm-chat-head');if(!head||head.querySelector('#gmBanOpen'))return;const b=document.createElement('button');b.id='gmBanOpen';b.type='button';b.title='المحظورون';b.textContent='🚫';b.style.cssText='border:0;background:none;font-size:19px;cursor:pointer;margin-inline-start:4px';b.onclick=()=>openBans(meta.groupId);head.appendChild(b)}
 setInterval(inject,700);inject();window.madaOpenGroupBans=openBans;
})();