/* Mada Groups v3 — private join requests, communities, admins, members, pinned posts */
(function(){
  let overlay=null,currentGroup=null;
  const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const toast=m=>window.madaToast?window.madaToast(m):console.log(m);
  const me=()=>window.user||null;
  async function openGroups(){
    if(!window.sb||!me()){toast('سجّل الدخول أولاً');return}
    overlay?.remove();overlay=document.createElement('div');overlay.className='groups-overlay';
    overlay.innerHTML='<div class="groups-shell"><header><div><h2>👥 المجموعات</h2><small>مجتمعات Mada — شارك، ناقش، وتواصل</small></div><div class="groups-head-actions"><button id="groupCreate">＋ إنشاء</button><button id="groupClose">×</button></div></header><div class="groups-search"><input id="groupsSearch" placeholder="ابحث عن مجموعة…"></div><div class="groups-tabs"><button class="active" data-tab="all">كل المجموعات</button><button data-tab="mine">مجموعاتي</button></div><div id="groupsContent" class="groups-content"></div></div>';
    document.body.appendChild(overlay);overlay.querySelector('#groupClose').onclick=closeGroups;overlay.onclick=e=>{if(e.target===overlay)closeGroups()};overlay.querySelector('#groupCreate').onclick=showCreate;overlay.querySelector('#groupsSearch').oninput=e=>loadGroups(e.target.value.trim(),overlay.querySelector('.groups-tabs .active')?.dataset.tab||'all');overlay.querySelectorAll('.groups-tabs button').forEach(b=>b.onclick=()=>{overlay.querySelectorAll('.groups-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');loadGroups(overlay.querySelector('#groupsSearch').value.trim(),b.dataset.tab)});await loadGroups();
  }
  function closeGroups(){overlay?.remove();overlay=null;currentGroup=null}
  async function loadGroups(search='',tab='all'){
    const box=overlay?.querySelector('#groupsContent');if(!box)return;box.innerHTML='<div class="groups-loading">جاري التحميل…</div>';
    let q=sb.from('groups').select('id,owner_id,name,description,avatar_url,cover_url,privacy,created_at').order('created_at',{ascending:false}).limit(80);if(search)q=q.ilike('name','%'+search.replace(/[%_]/g,'')+'%');const {data,error}=await q;if(error){box.innerHTML='<div class="groups-empty">تعذر تحميل المجموعات.</div>';return}
    const ids=(data||[]).map(g=>g.id);let members=[];if(ids.length){const r=await sb.from('group_members').select('group_id,user_id,role').in('group_id',ids);members=r.data||[]}
    const mine=new Set(members.filter(m=>m.user_id===me().id).map(m=>m.group_id));const counts=new Map();members.forEach(m=>counts.set(m.group_id,(counts.get(m.group_id)||0)+1));let rows=tab==='mine'?(data||[]).filter(g=>mine.has(g.id)):(data||[]);
    box.innerHTML=rows.map(g=>`<article class="group-card" data-id="${esc(g.id)}"><div class="group-avatar">${g.avatar_url?`<img src="${esc(g.avatar_url)}">`:'👥'}</div><div class="group-info"><h3>${esc(g.name)} ${g.privacy==='private'?'<span class="privacy-badge">🔒</span>':''}</h3><p>${esc(g.description||'مجتمع جديد على Mada')}</p><small>👤 ${counts.get(g.id)||0} عضو</small></div><button class="group-action" data-action="${mine.has(g.id)?'open':'join'}">${mine.has(g.id)?'فتح':(g.privacy==='private'?'طلب الانضمام':'انضمام')}</button></article>`).join('')||'<div class="groups-empty">لا توجد مجموعات هنا بعد.</div>';
    box.querySelectorAll('.group-card').forEach(c=>c.onclick=e=>{if(e.target.closest('.group-action'))return;openGroup(c.dataset.id)});box.querySelectorAll('.group-action').forEach(b=>b.onclick=async e=>{e.stopPropagation();const id=b.closest('.group-card').dataset.id;const g=(data||[]).find(x=>x.id===id);if(b.dataset.action==='join'){if(g?.privacy==='private'){const r=await sb.from('group_join_requests').upsert({group_id:id,user_id:me().id},{onConflict:'group_id,user_id'});if(r.error){toast('تعذر إرسال طلب الانضمام');return}toast('تم إرسال طلب الانضمام 🔒');return}const r=await sb.from('group_members').insert({group_id:id,user_id:me().id,role:'member'});if(r.error&&r.error.code!=='23505'){toast('تعذر الانضمام');return}toast('تم الانضمام 🎉');openGroup(id)}else openGroup(id)});
  }
  function showCreate(){const box=document.createElement('div');box.className='groups-modal';box.innerHTML='<div class="groups-dialog"><button class="gm-close">×</button><h2>إنشاء مجتمع جديد</h2><input id="gmName" maxlength="60" placeholder="اسم المجموعة"><textarea id="gmDesc" maxlength="300" placeholder="وصف المجموعة"></textarea><input id="gmAvatar" placeholder="رابط صورة المجموعة (اختياري)"><label class="privacy-choice"><input id="gmPrivate" type="checkbox"> 🔒 مجموعة خاصة</label><button id="gmSave" class="gm-primary">إنشاء المجموعة</button></div>';document.body.appendChild(box);box.querySelector('.gm-close').onclick=()=>box.remove();box.onclick=e=>{if(e.target===box)box.remove()};box.querySelector('#gmSave').onclick=async()=>{const name=box.querySelector('#gmName').value.trim();if(!name){toast('اكتب اسم المجموعة');return}const {data,error}=await sb.rpc('create_group_and_join',{p_name:name,p_description:box.querySelector('#gmDesc').value.trim(),p_avatar_url:box.querySelector('#gmAvatar').value.trim()||null});if(error){toast('تعذر إنشاء المجموعة');return}if(box.querySelector('#gmPrivate').checked)await sb.from('groups').update({privacy:'private'}).eq('id',data.id).eq('owner_id',me().id);box.remove();toast('تم إنشاء المجموعة 🎉');openGroup(data.id)} }
  async function openGroup(id){
    const {data:g,error}=await sb.from('groups').select('id,owner_id,name,description,avatar_url,cover_url,privacy,created_at').eq('id',id).single();if(error)return;
    currentGroup=g;const {data:members}=await sb.from('group_members').select('user_id,role').eq('group_id',id);const mine=(members||[]).find(m=>m.user_id===me().id);const isMember=!!mine,isOwner=g.owner_id===me().id,isAdmin=isOwner||mine?.role==='admin';
    const {data:posts}=isMember?await sb.from('posts').select('id,author_id,body,media_url,created_at,is_pinned,profiles!posts_author_id_fkey(display_name,avatar_url)').eq('group_id',id).order('is_pinned',{ascending:false}).order('created_at',{ascending:false}).limit(50):{data:[]};
    const joinText=g.privacy==='private'?'طلب الانضمام':'انضمام';
    overlay.querySelector('.groups-shell').innerHTML=`<header><div class="group-detail-head"><button id="groupBack">‹</button><div class="group-avatar big">${g.avatar_url?`<img src="${esc(g.avatar_url)}">`:'👥'}</div><div><h2>${esc(g.name)}</h2><small>${(members||[]).length} عضو · ${g.privacy==='private'?'🔒 خاصة':'🌐 عامة'}</small></div></div><button id="groupClose">×</button></header><div class="group-cover" style="${g.cover_url?`background-image:url('${esc(g.cover_url)}')`:''}"><div class="group-cover-shade"></div><div class="group-cover-content"><p>${esc(g.description||'لا يوجد وصف للمجموعة.')}</p><div class="group-buttons">${isMember?'<button id="groupLeave">مغادرة</button>':`<button id="groupJoin" class="gm-primary">${joinText}</button>`}${isAdmin?'<button id="groupMembers">👥 الأعضاء</button>':''}${isOwner?'<button id="groupEdit">✏️ تعديل</button><button id="groupDelete">حذف</button>':''}</div></div></div>${isMember?'<div class="group-composer"><textarea id="groupPostText" maxlength="2000" placeholder="اكتب منشورًا للمجموعة…"></textarea><button id="groupPostSend">نشر</button></div>':'<div class="group-join-note">انضم للمجموعة للمشاركة في النقاش والمنشورات.</div>'}<div id="groupPosts" class="group-posts">${renderPosts(posts||[],isAdmin)}</div>`;
    overlay.querySelector('#groupBack').onclick=loadGroups;overlay.querySelector('#groupClose').onclick=closeGroups;
    overlay.querySelector('#groupJoin')?.addEventListener('click',async()=>{if(g.privacy==='private'){const r=await sb.from('group_join_requests').upsert({group_id:id,user_id:me().id},{onConflict:'group_id,user_id'});if(r.error){toast('تعذر إرسال طلب الانضمام');return}toast('تم إرسال طلب الانضمام 🔒');return}const r=await sb.from('group_members').insert({group_id:id,user_id:me().id,role:'member'});if(r.error){toast('تعذر الانضمام');return}openGroup(id)});
    overlay.querySelector('#groupLeave')?.addEventListener('click',async()=>{if(isOwner){toast('مالك المجموعة لا يمكنه مغادرتها؛ احذفها أو انقل الملكية أولاً');return}await sb.from('group_members').delete().eq('group_id',id).eq('user_id',me().id);toast('غادرت المجموعة');loadGroups()});
    overlay.querySelector('#groupDelete')?.addEventListener('click',async()=>{if(!confirm('حذف المجموعة ومنشوراتها؟'))return;const r=await sb.from('groups').delete().eq('id',id);if(r.error){toast('تعذر حذف المجموعة');return}toast('تم حذف المجموعة');loadGroups()});
    overlay.querySelector('#groupEdit')?.addEventListener('click',()=>editGroup(g));overlay.querySelector('#groupMembers')?.addEventListener('click',()=>showMembers(id,g.owner_id));
    overlay.querySelector('#groupPostSend')?.addEventListener('click',async()=>{const body=overlay.querySelector('#groupPostText').value.trim();if(!body)return;const r=await sb.from('posts').insert({author_id:me().id,body,media_url:null,visibility:'public',group_id:id});if(r.error){toast('تعذر نشر المنشور');return}openGroup(id)});
    overlay.querySelectorAll('[data-pin]').forEach(b=>b.onclick=async()=>{const pid=b.dataset.pin;const r=await sb.from('posts').update({is_pinned:b.dataset.state!=='true'}).eq('id',pid);if(r.error){toast('لا يمكن تثبيت هذا المنشور من حسابك');return}openGroup(id)});
  }
  function renderPosts(posts,isAdmin){return posts.map(p=>`<article class="group-post ${p.is_pinned?'pinned':''}"><div class="gp-author"><span>${esc((p.profiles?.display_name||'م').charAt(0))}</span><div><b>${esc(p.profiles?.display_name||'مستخدم Mada')}</b><small>${esc(new Date(p.created_at).toLocaleString('ar-EG',{dateStyle:'short',timeStyle:'short'}))}</small></div>${p.is_pinned?'<em>📌 مثبت</em>':''}</div><p>${esc(p.body||'')}</p>${p.media_url?`<img src="${esc(p.media_url)}" loading="lazy">`:''}${isAdmin?`<button class="pin-post" data-pin="${esc(p.id)}" data-state="${p.is_pinned?'true':'false'}">${p.is_pinned?'إلغاء التثبيت':'📌 تثبيت'}</button>`:''}</article>`).join('')||'<div class="groups-empty">لا توجد منشورات في المجموعة بعد.</div>'}
  function editGroup(g){const box=document.createElement('div');box.className='groups-modal';box.innerHTML=`<div class="groups-dialog"><button class="gm-close">×</button><h2>تعديل المجموعة</h2><input id="geName" maxlength="60" value="${esc(g.name)}"><textarea id="geDesc" maxlength="300">${esc(g.description||'')}</textarea><input id="geAvatar" placeholder="رابط صورة المجموعة" value="${esc(g.avatar_url||'')}"><input id="geCover" placeholder="رابط صورة الغلاف" value="${esc(g.cover_url||'')}"><select id="gePrivacy"><option value="public" ${g.privacy==='public'?'selected':''}>🌐 عامة</option><option value="private" ${g.privacy==='private'?'selected':''}>🔒 خاصة</option></select><button id="geSave" class="gm-primary">حفظ التغييرات</button></div>`;document.body.appendChild(box);box.querySelector('.gm-close').onclick=()=>box.remove();box.querySelector('#geSave').onclick=async()=>{const r=await sb.from('groups').update({name:box.querySelector('#geName').value.trim(),description:box.querySelector('#geDesc').value.trim(),avatar_url:box.querySelector('#geAvatar').value.trim()||null,cover_url:box.querySelector('#geCover').value.trim()||null,privacy:box.querySelector('#gePrivacy').value}).eq('id',g.id).eq('owner_id',me().id);if(r.error){toast('تعذر حفظ التغييرات');return}box.remove();openGroup(g.id)}}
  async function showMembers(id,ownerId){
    const r=await sb.from('group_members').select('user_id,role,created_at').eq('group_id',id);const ms=r.data||[];const ids=ms.map(x=>x.user_id);let profiles=[];if(ids.length){const p=await sb.from('profiles').select('id,display_name,avatar_url').in('id',ids);profiles=p.data||[]}const map=new Map(profiles.map(p=>[p.id,p]));
    const pending=await sb.from('group_join_requests').select('user_id,created_at').eq('group_id',id);const requests=pending.data||[];const reqIds=requests.map(x=>x.user_id);let reqProfiles=[];if(reqIds.length){const p=await sb.from('profiles').select('id,display_name,avatar_url').in('id',reqIds);reqProfiles=p.data||[]}const reqMap=new Map(reqProfiles.map(p=>[p.id,p]));
    const box=document.createElement('div');box.className='groups-modal';box.innerHTML=`<div class="groups-dialog"><button class="gm-close">×</button><h2>👥 أعضاء المجموعة</h2>${requests.length?`<h3>طلبات الانضمام (${requests.length})</h3><div class="member-list">${requests.map(q=>{const p=reqMap.get(q.user_id)||{};return `<div class="member-row"><div class="member-avatar">${p.avatar_url?`<img src="${esc(p.avatar_url)}">`:'👤'}</div><div><b>${esc(p.display_name||'مستخدم')}</b><small>طلب انضمام</small></div><button type="button" data-approve="${esc(q.user_id)}">قبول</button><button type="button" data-reject="${esc(q.user_id)}">رفض</button></div>`}).join('')}</div>`:''}<div class="member-list">${ms.map(m=>{const p=map.get(m.user_id)||{};return `<div class="member-row"><div class="member-avatar">${p.avatar_url?`<img src="${esc(p.avatar_url)}">`:'👤'}</div><div><b>${esc(p.display_name||'مستخدم')}</b><small>${m.role==='owner'?'👑 مالك':m.role==='admin'?'🛡️ مشرف':'عضو'}</small></div>${m.user_id!==me().id&&m.user_id!==ownerId?`<select data-member="${esc(m.user_id)}"><option value="member" ${m.role==='member'?'selected':''}>عضو</option><option value="admin" ${m.role==='admin'?'selected':''}>مشرف</option></select>`:''}</div>`}).join('')}</div></div>`;
    document.body.appendChild(box);box.querySelector('.gm-close').onclick=()=>box.remove();
    box.querySelectorAll('[data-member]').forEach(s=>s.onchange=async()=>{const r=await sb.from('group_members').update({role:s.value}).eq('group_id',id).eq('user_id',s.dataset.member);if(r.error)toast('لا يمكن تغيير الدور');else toast('تم تحديث دور العضو')});
    box.querySelectorAll('[data-approve]').forEach(b=>b.onclick=async()=>{const uid=b.dataset.approve;const a=await sb.from('group_members').insert({group_id:id,user_id:uid,role:'member'});if(a.error&&a.error.code!=='23505'){toast('تعذر قبول الطلب');return}await sb.from('group_join_requests').delete().eq('group_id',id).eq('user_id',uid);toast('تم قبول الطلب ✅');box.remove();showMembers(id,ownerId)});
    box.querySelectorAll('[data-reject]').forEach(b=>b.onclick=async()=>{const uid=b.dataset.reject;const a=await sb.from('group_join_requests').delete().eq('group_id',id).eq('user_id',uid);if(a.error){toast('تعذر رفض الطلب');return}toast('تم رفض الطلب');box.remove();showMembers(id,ownerId)});
  }
  function addButton(){const top=document.querySelector('.top-actions');if(!top||top.querySelector('#groupsBtn'))return;const b=document.createElement('button');b.id='groupsBtn';b.type='button';b.textContent='👥';b.title='المجموعات';b.setAttribute('aria-label','المجموعات');b.onclick=openGroups;top.insertBefore(b,document.querySelector('#exploreBtn')?.nextSibling||top.firstChild)}
  document.addEventListener('DOMContentLoaded',()=>{addButton();new MutationObserver(addButton).observe(document.body,{childList:true,subtree:true})});window.openGroups=openGroups;
})();