/* Mada Messenger media + voice + typing + presence + read receipts */
(function(){
  const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  let sb=null,user=null,current=null,channel=null,presenceTimer=null,typingTimer=null,recorder=null,recordChunks=[];
  const get=()=>{sb=window.sb||sb;user=window.user||user;return sb&&user};
  const toast=m=>window.showToast?window.showToast(m):console.log(m);
  const time=v=>{try{return new Date(v).toLocaleTimeString('ar-EG',{hour:'2-digit',minute:'2-digit'})}catch{return ''}};
  function avatar(p){return p?.avatar_url?'<img src="'+esc(p.avatar_url)+'" alt="">':esc((p?.display_name||p?.username||'م').charAt(0))}
  function renderMessage(m){const mine=m.sender_id===user.id,type=m.message_type||'text';let content='';if(type==='image'&&m.media_url)content='<img class="mm-media-img" src="'+esc(m.media_url)+'" alt="صورة">';else if(type==='audio'&&m.media_url)content='<audio class="mm-audio" controls preload="metadata" src="'+esc(m.media_url)+'"></audio>';else if(type==='file'&&m.media_url)content='<a class="mm-file" href="'+esc(m.media_url)+'" target="_blank" rel="noopener">📎 <span>'+esc(m.file_name||'ملف')+'</span></a>';if(m.body)content+=(content?'<div class="mm-media-caption">':'<div>')+esc(m.body)+'</div>';return '<div class="mm-bubble '+(mine?'mine':'theirs')+'" data-message-id="'+esc(m.id)+'">'+content+'<small>'+time(m.created_at)+(mine?'<span class="mm-read">'+(m.read_at?'✓✓':'✓')+'</span>':'')+'</small></div>'}
  async function upload(file,type){if(!get())throw new Error('غير مسجل');if(file.size>15*1024*1024)throw new Error('الحد الأقصى للملف 15 ميجابايت');const ext=(file.name.split('.').pop()||'bin').toLowerCase().replace(/[^a-z0-9]/g,'')||'bin';const path=user.id+'/'+crypto.randomUUID()+'.'+ext;const up=await sb.storage.from('messages-media').upload(path,file,{contentType:file.type||'application/octet-stream',upsert:false});if(up.error)throw up.error;return sb.storage.from('messages-media').getPublicUrl(path).data.publicUrl}
  async function sendMedia(file,type){if(!current||!file)return;try{const url=await upload(file,type);const payload={conversation_id:current.cid,sender_id:user.id,body:'',message_type:type,media_url:url,file_name:file.name||null,file_size:file.size||null};const {data,error}=await sb.from('messages').insert(payload).select('id,conversation_id,sender_id,body,created_at,read_at,message_type,media_url,file_name,file_size').single();if(error)throw error;$('mmMessages').insertAdjacentHTML('beforeend',renderMessage(data));scrollBottom()}catch(e){console.error(e);toast('تعذر إرسال الملف: '+(e.message||''))}}
  async function sendText(){if(!get()||!current)return;const input=$('mmInput'),body=input.value.trim();if(!body)return;try{const {data,error}=await sb.from('messages').insert({conversation_id:current.cid,sender_id:user.id,body,message_type:'text'}).select('id,conversation_id,sender_id,body,created_at,read_at,message_type,media_url,file_name,file_size').single();if(error)throw error;input.value='';input.style.height='auto';$('mmMessages').insertAdjacentHTML('beforeend',renderMessage(data));scrollBottom();setTyping(false)}catch(e){console.error(e);toast('تعذر إرسال الرسالة')}}
  async function markRead(){if(!current||!get())return;const {error}=await sb.from('messages').update({read_at:new Date().toISOString()}).eq('conversation_id',current.cid).neq('sender_id',user.id).is('read_at',null);if(error)console.warn(error);document.querySelectorAll('.mm-bubble.mine .mm-read').forEach(x=>x.textContent='✓✓')}
  async function setTyping(on){if(!current||!get())return;try{await sb.rpc('touch_my_presence',{p_conversation_id:current.cid,p_typing:on})}catch(e){console.warn(e)}}
  function startPresence(){if(!get())return;const ping=()=>sb.rpc('touch_my_presence',{p_conversation_id:current?.cid||null,p_typing:false}).catch(()=>{});ping();clearInterval(presenceTimer);presenceTimer=setInterval(ping,25000)}
  function subscribe(){if(channel)sb.removeChannel(channel);channel=sb.channel('mada-messenger-'+current.cid).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:'conversation_id=eq.'+current.cid},p=>{if(p.new.sender_id!==user.id){const out=$('mmMessages');out.querySelector('.chat-empty')?.remove();out.insertAdjacentHTML('beforeend',renderMessage(p.new));scrollBottom();markRead()}}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'messages',filter:'conversation_id=eq.'+current.cid},p=>{if(p.new.sender_id===user.id&&p.new.read_at){const row=document.querySelector('[data-message-id="'+CSS.escape(p.new.id)+'"] .mm-read');if(row)row.textContent='✓✓'}}).subscribe();
    const pc=sb.channel('mada-presence-'+current.cid).on('postgres_changes',{event:'*',schema:'public',table:'user_presence'},()=>refreshStatus()).subscribe();channel=channel;window._madaPresenceChannel=pc;refreshStatus()
  }
  async function refreshStatus(){if(!current||!get())return;const {data}=await sb.from('user_presence').select('is_online,last_seen,typing_conversation_id').eq('user_id',current.uid).maybeSingle();const el=$('mmOnlineStatus');if(!el)return;if(data?.typing_conversation_id===current.cid){el.textContent='يكتب الآن…';el.className='mm-status typing'}else if(data?.is_online&&data?.last_seen&&Date.now()-new Date(data.last_seen).getTime()<70000){el.textContent='متصل الآن';el.className='mm-status online'}else{el.textContent=data?.last_seen?'آخر ظهور '+time(data.last_seen):'غير متصل';el.className='mm-status'}}
  function stopRecording(){if(recorder&&recorder.state!=='inactive')recorder.stop()}
  async function toggleRecord(){if(recorder&&recorder.state==='recording'){stopRecording();return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){toast('التسجيل الصوتي غير مدعوم على هذا الجهاز');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});recordChunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>e.data.size&&recordChunks.push(e.data);recorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(recordChunks,{type:recorder.mimeType||'audio/webm'});const file=new File([blob],'voice-'+Date.now()+'.webm',{type:blob.type});$('mmRecord').textContent='🎤';await sendMedia(file,'audio')};recorder.start();$('mmRecord').textContent='⏹️';toast('جاري التسجيل… اضغط مرة أخرى للإيقاف')}catch(e){console.error(e);toast('اسمح للتطبيق باستخدام الميكروفون')}}
  function bindMedia(){
    const plus=$('mmPlus'),file=$('mmFileInput'),img=$('mmImageInput'),record=$('mmRecord');if(plus&&!plus.dataset.bound){plus.dataset.bound='1';plus.onclick=()=>{const menu=$('mmAttachMenu');if(menu)menu.hidden=!menu.hidden}}
    if(file&&!file.dataset.bound){file.dataset.bound='1';file.onchange=e=>{const f=e.target.files[0];if(f)sendMedia(f,'file');e.target.value=''}}
    if(img&&!img.dataset.bound){img.dataset.bound='1';img.onchange=e=>{const f=e.target.files[0];if(f)sendMedia(f,'image');e.target.value=''}}
    if(record&&!record.dataset.bound){record.dataset.bound='1';record.onclick=toggleRecord}
    const input=$('mmInput');if(input&&!input.dataset.typing){input.dataset.typing='1';input.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,110)+'px';clearTimeout(typingTimer);setTyping(true);typingTimer=setTimeout(()=>setTyping(false),1200)})}
  }
  function scrollBottom(){const x=$('mmMessages');if(x)setTimeout(()=>x.scrollTop=x.scrollHeight,20)}
  function enhance(){if(!get())return;const chat=$('mmChat');if(!chat)return;let compose=$('.mm-compose');if(!compose)return;if(!$('mmFileInput')){const a=document.createElement('input');a.id='mmFileInput';a.type='file';a.hidden=true;document.body.appendChild(a)}if(!$('mmImageInput')){const a=document.createElement('input');a.id='mmImageInput';a.type='file';a.accept='image/*';a.hidden=true;document.body.appendChild(a)}if(!$('mmAttachMenu')){const m=document.createElement('div');m.id='mmAttachMenu';m.className='mm-attach-menu';m.hidden=true;m.innerHTML='<button type="button" id="mmPickImage">🖼️ صورة</button><button type="button" id="mmPickFile">📎 ملف</button>';compose.appendChild(m);$('mmPickImage').onclick=()=>{$('mmAttachMenu').hidden=true;$('mmImageInput').click()};$('mmPickFile').onclick=()=>{$('mmAttachMenu').hidden=true;$('mmFileInput').click()}}if(!$('mmRecord')){const r=document.createElement('button');r.id='mmRecord';r.type='button';r.className='mm-record';r.textContent='🎤';compose.insertBefore(r,$('mmSend'))}if(!$('mmOnlineStatus')){const h=$('mmChatUser');const s=document.createElement('span');s.id='mmOnlineStatus';s.className='mm-status';h?.appendChild(s)}bindMedia()}
  function bindOpen(){const b=$('msgBtn');if(!b||b.dataset.mmMediaBound)return;b.dataset.mmMediaBound='1';b.addEventListener('click',()=>setTimeout(enhance,100),true)}
  function hook(){bindOpen();enhance();startPresence()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',hook);else hook();[500,1500,3000].forEach(x=>setTimeout(hook,x));
  window.madaMessengerMedia={sendMedia,toggleRecord,markRead};
})();