/* Mada Profile Runtime v10 — single clean modern profile runtime. */
(function(){'use strict';
if(window.__MADA_PROFILE_V10)return;window.__MADA_PROFILE_V10=true;
const C=()=>window.MADA_SUPABASE_CLIENT||window.sb,$=id=>document.getElementById(id),show=(t,b)=>window.showModal?.(t,b);
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const ini=s=>(String(s||'م').trim()[0]||'م');let me=null;const cache=new Map(),pending=new Map(),TTL=20000;
async function auth(force=false){if(me&&!force)return me;try{me=(await C().auth.getUser()).data?.user||null}catch{me=null}return me}
async function getProfile(id,force=false){if(!force&&cache.has(id)&&Date.now()-cache.get(id).at<TTL)return cache.get(id).data;if(!force&&pending.has(id))return pending.get(id);const q=(async()=>{const r=await C().from('profiles').select('id,display_name,username,bio,avatar_url,cover_url,city,role,is_verified,verification_type,verification_expires_at,created_at,updated_at').eq('id',id).maybeSingle();if(r.error)throw r.error;if(r.data)cache.set(id,{at:Date.now(),data:r.data});return r.data})();pending.set(id,q);try{return await q}catch(e){console.error('[Mada Profile]',e);return null}finally{pending.delete(id)}}
const isVerified=p=>{const role=String(p?.role||'').toLowerCase();if(role==='admin'||role==='super_admin')return true;if(!p?.is_verified)return false;return !(String(p.verification_type||'').toLowerCase()==='premium'&&p.verification_expires_at&&new Date(p.verification_expires_at)<=new Date())};
const badge=p=>isVerified(p)?`<span class="mada-h4-badge" aria-label="حساب موثق"><svg viewBox="0 0 24 24"><path class="badge-shape" d="M12 2l2 2 3-.5.7 2.8 2.6 1.4-1.2 2.7 1.2 2.7-2.6 1.4-.7 2.8-3-.5-2 2-2-2-3 .5-.7-2.8-2.6-1.4 1.2-2.7-1.2-2.7 2.6-1.4.7-2.8 3 .5z"/><path class="badge-check" d="M7.2 12.2l3.1 3.1 6.5-7"/></svg></span>`:'';
function shell(p,own,r){const actions=own?'<button id="mfpEdit" class="primary" type="button">✏️ تعديل الملف</button>':`<button id="mfpFriend" class="primary" type="button">${r.friend?.status==='accepted'?'✓ أصدقاء':r.friend?.status==='pending'?'⏳ طلب مُرسل':'👥 إضافة صديق'}</button><button id="mfpMsg" type="button">💬 رسالة</button><button id="mfpFollow" type="button">${r.follow?'✓ إلغاء المتابعة':'➕ متابعة'}</button>`;return `<div class="mada-fast-profile"><div class="mada-fast-cover"${p.cover_url?` style="background-image:url('${esc(p.cover_url)}')!important"`:''}><span class="mada-cover-label">Mada</span></div><div class="mada-fast-main"><div class="mada-fast-avatar">${p.avatar_url?`<img src="${esc(p.avatar_url)}" alt="" decoding="async">`:ini(p.display_name||p.username)}</div><h2>${esc(p.display_name||p.username||'مستخدم Mada')} ${badge(p)}</h2><div class="mada-fast-meta">${p.username?`<span dir="ltr">@${esc(p.username)}</span>`:''}${p.city?`<span>📍 ${esc(p.city)}</span>`:''}</div>${p.bio?`<div class="mada-fast-bio">${esc(p.bio)}</div>`:''}<div class="mada-fast-stats"><button type="button" data-mpf-list="friends" data-mpf-profile="${esc(p.id)}"><b id="mfpFriendsCount">…</b><span>أصدقاء</span></button><button type="button" data-mpf-list="followers" data-mpf-profile="${esc(p.id)}"><b id="mfpFollowersCount">…</b><span>متابعون</span></button><button type="button" data-mpf-list="following" data-mpf-profile="${esc(p.id)}"><b id="mfpFollowingCount">…</b><span>يتابع</span></button><button id="mfpPostsStat" type="button"><b id="mfpPostsCount">…</b><span>منشور</span></button></div><div class="mada-fast-actions">${actions}<button id="mfpShare" type="button">↗️ مشاركة الملف</button></div></div><div class="mada-fast-tabs"><button id="mfpPostsTab" class="active" type="button">المنشورات</button><button id="mfpAboutTab" type="button">حول</button></div><div id="mfpContent" class="mada-fast-posts"><div class="mada-fast-loading">جاري تحميل المحتوى…</div></div></div>`}
function postsHtml(rows){if(!rows.length)return'<div class="mada-fast-loading">لا توجد منشورات بعد.</div>';return rows.map(x=>`<article class="mada-fast-post">${x.is_pinned?'<small class="mada-pinned">📌 منشور مثبت</small>':''}<p>${esc(x.body||'')}</p>${x.media_url?`<img src="${esc(x.media_url)}" loading="lazy" decoding="async" alt="">`:''}<time>${x.created_at?esc(new Date(x.created_at).toLocaleString('ar-EG')):''}</time></article>`).join('')}
async function loadData(id){const c=C();const [posts,total,friends,followers,following]=await Promise.all([c.from('posts').select('id,body,media_url,created_at,is_pinned').eq('author_id',id).order('created_at',{ascending:false}).limit(10),c.from('posts').select('id',{count:'exact',head:true}).eq('author_id',id),c.from('friendships').select('id',{count:'exact',head:true}).eq('status','accepted').or(`requester_id.eq.${id},addressee_id.eq.${id}`),c.from('follows').select('follower_id',{count:'exact',head:true}).eq('following_id',id),c.from('follows').select('following_id',{count:'exact',head:true}).eq('follower_id',id)]);return{posts:posts.data||[],postCount:total.count||0,friends:friends.count||0,followers:followers.count||0,following:following.count||0}}
async function open(id){const u=await auth(true);if(!u)return show('👤 الملف الشخصي','<div class="empty">يجب تسجيل الدخول أولاً.</div>');const target=id||u.id;window.__MADA_PROFILE_ID=target;window.__MADA_CURRENT_USER_ID=u.id;const p=await getProfile(target);if(!p)return show('👤 الملف الشخصي','<div class="empty">تعذر تحميل الملف الشخصي.</div>');const own=target===u.id,r=await relation(target,u);show('👤 الملف الشخصي',shell(p,own,r));const content=$('mfpContent');loadData(target).then(data=>{[['mfpPostsCount',data.postCount],['mfpFriendsCount',data.friends],['mfpFollowersCount',data.followers],['mfpFollowingCount',data.following]].forEach(([i,v])=>{if($(i))$(i).textContent=v});if(content)content.innerHTML=postsHtml(data.posts);$('mfpPostsTab')?.addEventListener('click',()=>{activate('mfpPostsTab');content.innerHTML=postsHtml(data.posts)});$('mfpPostsStat')?.addEventListener('click',()=>{activate('mfpPostsTab');content.innerHTML=postsHtml(data.posts);content.scrollIntoView({behavior:'smooth',block:'start'})})}).catch(console.error);$('mfpAboutTab')?.addEventListener('click',()=>{activate('mfpAboutTab');if(content)content.innerHTML=`<div class="mada-about"><div>📝 ${esc(p.bio||'لا توجد نبذة حتى الآن.')}</div>${p.city?`<div>📍 ${esc(p.city)}</div>`:''}<div>🗓️ عضو منذ ${esc(new Date(p.created_at||Date.now()).toLocaleDateString('ar-EG',{year:'numeric',month:'long'}))}</div></div>`});$('mfpEdit')?.addEventListener('click',()=>edit(p,target));$('mfpMsg')?.addEventListener('click',()=>window.openChat?.(target));$('mfpFriend')?.addEventListener('click',()=>window.MadaProfileActionsV3?.friend?.(target));$('mfpFollow')?.addEventListener('click',()=>window.MadaProfileActionsV3?.follow?.(target));$('mfpShare')?.addEventListener('click',()=>share(p,target))}
function activate(id){document.querySelectorAll('#modal .mada-fast-tabs button').forEach(x=>x.classList.toggle('active',x.id===id))}
async function share(p,id){const url=location.origin+location.pathname+'?profile='+encodeURIComponent(id);try{if(navigator.share)await navigator.share({title:p.display_name||'Mada',url});else{await navigator.clipboard.writeText(url);alert('تم نسخ رابط الملف ✓')}}catch{}}
function edit(p,id){show('✏️ تعديل الملف الشخصي',`<div class="edit-profile"><label>الاسم<input id="rootName" maxlength="80" value="${esc(p.display_name||'')}"></label><label>اسم المستخدم<input id="rootUsername" maxlength="40" value="${esc(p.username||'')}"></label><label>المدينة<input id="rootCity" maxlength="80" value="${esc(p.city||'')}"></label><label>نبذة عني<textarea id="rootBio" maxlength="500">${esc(p.bio||'')}</textarea></label><button id="rootSave" class="primary wide" type="button">حفظ التعديلات</button><div id="rootSaveMsg" class="muted" aria-live="polite"></div></div>`);const btn=$('rootSave');if(!btn)return;btn.onclick=async()=>{if(btn.disabled)return;const msg=$('rootSaveMsg');const name=$('rootName').value.trim(),username=$('rootUsername').value.trim().replace(/^@/,'');if(!name){msg.textContent='الاسم مطلوب.';return}if(username&&!/^[a-zA-Z0-9_.]{3,40}$/.test(username)){msg.textContent='اسم المستخدم يجب أن يكون 3–40 حرفًا إنجليزيًا أو رقمًا أو _ أو .';return}btn.disabled=true;btn.textContent='جاري الحفظ…';msg.textContent='';try{const payload={display_name:name,username:username||null,city:$('rootCity').value.trim()||null,bio:$('rootBio').value.trim()||null,updated_at:new Date().toISOString()};const r=await C().from('profiles').update(payload).eq('id',id).select('id,display_name,username,bio,avatar_url,cover_url,city,role,is_verified,verification_type,verification_expires_at,created_at,updated_at').maybeSingle();if(r.error)throw r.error;if(!r.data)throw new Error('لم يتم حفظ التعديلات. قد تكون صلاحيات قاعدة البيانات تمنع التحديث.');cache.set(id,{at:Date.now(),data:r.data});msg.textContent='تم الحفظ بنجاح ✓';await new Promise(res=>setTimeout(res,300));await open(id)}catch(e){btn.disabled=false;btn.textContent='حفظ التعديلات';msg.textContent=e?.code==='23505'?'اسم المستخدم مستخدم بالفعل.':`تعذر الحفظ: ${e?.message||'خطأ غير معروف'}`}}}
async function openOwn(){const u=await auth(true);return u?open(u.id):open()}
window.ProfileUI={open,openOwn,init:auth,edit:openOwn,refresh:id=>{if(id)cache.delete(id);else cache.clear();return open(id)}};window.openProfile=open;window.MADA_PROFILE_ROOT_FIXED=true;
function guard(){const nav=$('profileNav');if(!nav||nav.dataset.madaOwnGuard==='10')return;nav.dataset.madaOwnGuard='10';nav.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();openOwn()},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',guard,{once:true});else guard();auth();
})();