(() => {
  let reelsObserver = null;
  let reelTimers = new WeakMap();
  const esc = value => String(value ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
  const currentUser=()=>typeof user!=='undefined'?user:null;
  const toast=m=>typeof window.showMadaToast==='function'?window.showMadaToast(m):console.log(m);
  function setupAutoPreviewReels(root=document){if(reelsObserver)reelsObserver.disconnect();const videos=root.querySelectorAll('.reel-video-preview');if(!('IntersectionObserver'in window))return;reelsObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{const v=entry.target;if(reelTimers.has(v)){clearTimeout(reelTimers.get(v));reelTimers.delete(v)}if(entry.isIntersecting){v.muted=true;v.currentTime=0;v.play().then(()=>{const t=setTimeout(()=>{v.pause();v.currentTime=0;reelTimers.delete(v)},2000);reelTimers.set(v,t)}).catch(()=>{})}else{v.pause();v.currentTime=0}}),{threshold:.6});videos.forEach(v=>reelsObserver.observe(v))}
  async function loadReels(){const row=document.getElementById('reelsRow');if(!row||typeof sb==='undefined')return;const {data,error}=await sb.from('reels').select('id,author_id,video_url,caption,created_at,profiles(display_name)').order('created_at',{ascending:false}).limit(30);if(error){console.error(error);row.innerHTML='<div class="reel-empty">تعذر تحميل الريلز</div>';return}if(!data?.length){row.innerHTML='<div class="reel-empty">لا توجد ريلز متاحة حالياً</div>';return}row.innerHTML=data.map(r=>`<article class="reel-card" data-reel-id="${esc(r.id)}"><video class="reel-video-preview" src="${esc(r.video_url)}" muted playsinline preload="metadata"></video><div class="reel-badge">🎬 ريلز</div><div class="reel-overlay-info"><span class="reel-author">@${esc(r.profiles?.display_name||'مستخدم')}</span>${r.caption?`<div>${esc(r.caption)}</div>`:''}</div><div class="reel-actions"><button type="button" onclick="toggleReelLike('${esc(r.id)}',this)">❤️ <span class="reel-like-count">0</span></button><button type="button" onclick="showReelComments('${esc(r.id)}')">💬 <span class="reel-comment-count">0</span></button><button type="button" onclick="shareReel('${esc(r.id)}')">↗️</button></div></article>`).join('');await loadReelCounts(data);setupAutoPreviewReels(row);setupReelGestures(row)}
  async function loadReelCounts(reels){const ids=reels.map(r=>r.id);const [{data:likes},{data:comments}]=await Promise.all([sb.from('reel_likes').select('reel_id').in('reel_id',ids),sb.from('reel_comments').select('reel_id').in('reel_id',ids)]);const lc={},cc={};(likes||[]).forEach(x=>lc[x.reel_id]=(lc[x.reel_id]||0)+1);(comments||[]).forEach(x=>cc[x.reel_id]=(cc[x.reel_id]||0)+1);reels.forEach(r=>{const c=document.querySelector(`.reel-card[data-reel-id="${r.id}"]`);if(c){c.querySelector('.reel-like-count').textContent=lc[r.id]||0;c.querySelector('.reel-comment-count').textContent=cc[r.id]||0}})}
  function setupReelGestures(row){let startY=0;let moving=false;row.ontouchstart=e=>{if(e.touches.length===1){startY=e.touches[0].clientY;moving=true}};row.ontouchend=e=>{if(!moving)return;moving=false;const dy=e.changedTouches[0].clientY-startY;if(Math.abs(dy)<45)return;row.scrollBy({top:dy<0?window.innerHeight:-window.innerHeight,behavior:'smooth'})}}
  window.openReelsSection=function(){const s=document.getElementById('reelsSection');if(!s)return;s.classList.add('is-open');loadReels();document.body.classList.add('reels-view-open')};
  window.closeReelsSection=function(){const s=document.getElementById('reelsSection');if(!s)return;s.classList.remove('is-open');document.body.classList.remove('reels-view-open');const r=document.getElementById('reelsRow');if(r)r.scrollTo({top:0,behavior:'instant'})};
  window.toggleReelLike=async function(id,b){const u=currentUser();if(!u){toast('سجل الدخول أولاً');return}const {data:ex}=await sb.from('reel_likes').select('reel_id').eq('reel_id',id).eq('user_id',u.id).maybeSingle();if(ex)await sb.from('reel_likes').delete().eq('reel_id',id).eq('user_id',u.id);else await sb.from('reel_likes').insert({reel_id:id,user_id:u.id});const {count}=await sb.from('reel_likes').select('*',{count:'exact',head:true}).eq('reel_id',id);b.querySelector('.reel-like-count').textContent=count||0};
  window.showReelComments=async function(id){const u=currentUser();if(!u){toast('سجل الدخول أولاً');return}const body=prompt('اكتب تعليقك على الريلز');if(!body?.trim())return;const {error}=await sb.from('reel_comments').insert({reel_id:id,user_id:u.id,body:body.trim()});toast(error?'تعذر إضافة التعليق':'تم إضافة التعليق');if(!error)loadReels()};
  window.shareReel=async function(id){const u=currentUser();if(!u){toast('سجل الدخول أولاً');return}const {error}=await sb.from('reel_shares').upsert({reel_id:id,user_id:u.id},{onConflict:'reel_id,user_id'});if(error){toast('تعذر تسجيل المشاركة');return}const {data}=await sb.from('reels').select('video_url').eq('id',id).single();try{if(data?.video_url)await navigator.clipboard.writeText(data.video_url);toast('تمت المشاركة ونسخ الرابط ↗️')}catch{toast('تم تسجيل المشاركة ↗️')}};
  window.createReel=async function(file,caption=''){const u=currentUser();if(!u||!file){toast(!u?'سجل الدخول أولاً':'اختر فيديو');return false}if(!file.type.startsWith('video/')){toast('اختر فيديو فقط');return false}if(file.size>50*1024*1024){toast('حجم الفيديو يجب ألا يتجاوز 50MB');return false}const ext=(file.name.split('.').pop()||'mp4').toLowerCase().replace(/[^a-z0-9]/g,'')||'mp4';const path=`${u.id}/${crypto.randomUUID()}.${ext}`;const {error:up}=await sb.storage.from('reels').upload(path,file,{contentType:file.type,upsert:false});if(up){toast('تعذر رفع الفيديو. تأكد من Storage Bucket باسم reels');return false}const {data:p}=sb.storage.from('reels').getPublicUrl(path);const {error}=await sb.from('reels').insert({author_id:u.id,video_url:p.publicUrl,caption:caption.trim()||null});if(error){toast('تعذر حفظ الريلز');return false}toast('تم نشر الريلز بنجاح 🎬');await loadReels();return true};
  window.openReelUploader=function(){let i=document.getElementById('reelUploadInput');if(!i){i=document.createElement('input');i.id='reelUploadInput';i.type='file';i.accept='video/*';i.hidden=true;document.body.appendChild(i);i.onchange=async()=>{const f=i.files?.[0];if(!f)return;await createReel(f,prompt('اكتب وصف الريلز (اختياري)')||'');i.value=''}}i.click()};
  window.openFullReel=function(v){if(!v)return;v.muted=false;v.currentTime=0;const p=v.play();if(p?.catch)p.catch(()=>{});if(v.requestFullscreen)v.requestFullscreen().catch?.(()=>{})};
  window.setupAutoPreviewReels=setupAutoPreviewReels;window.loadReels=loadReels;
  document.addEventListener('DOMContentLoaded',()=>{setupAutoPreviewReels();setTimeout(loadReels,500)});
})();