(() => {
  let reelsObserver=null;
  const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
  const toast=m=>typeof window.showMadaToast==='function'?window.showMadaToast(m):console.log(m);
  async function getCurrentUser(){try{const {data,error}=await sb.auth.getUser();return error?null:data?.user||null}catch{return null}}
  function playOnly(v){document.querySelectorAll('#reelsRow .reel-video-preview').forEach(x=>{if(x!==v){x.pause();x.muted=true}});v.muted=false;v.play().catch(()=>{})}
  function toggleSound(v){if(v.paused){playOnly(v);return}v.muted=!v.muted;toast(v.muted?'🔇 الصوت مكتوم':'🔊 الصوت يعمل')}
  function setupAutoPreviewReels(root=document){if(reelsObserver)reelsObserver.disconnect();const videos=root.querySelectorAll('.reel-video-preview');if(!('IntersectionObserver'in window))return;reelsObserver=new IntersectionObserver(es=>es.forEach(e=>{const v=e.target;if(e.isIntersecting&&e.intersectionRatio>=.6){document.querySelectorAll('#reelsRow .reel-video-preview').forEach(x=>{if(x!==v){x.pause();x.muted=true}});v.muted=true;v.play().catch(()=>{})}else{v.pause();v.muted=true}}),{threshold:[.25,.6,.9]});videos.forEach(v=>{v.addEventListener('click',e=>{e.preventDefault();toggleSound(v)});v.addEventListener('play',()=>document.querySelectorAll('#reelsRow .reel-video-preview').forEach(x=>{if(x!==v)x.pause() }));v.addEventListener('ended',()=>{const n=v.closest('.reel-card')?.nextElementSibling;if(n)n.scrollIntoView({behavior:'smooth',block:'start'})});reelsObserver.observe(v)})}
  async function deleteReel(id,videoUrl,card){const u=await getCurrentUser();if(!u){toast('سجل الدخول أولاً');return}const reel=await sb.from('reels').select('id,author_id,video_url').eq('id',id).single();if(reel.error||!reel.data){toast('الريلز غير موجود');return}if(reel.data.author_id!==u.id){toast('لا يمكنك حذف هذا الريلز');return}if(!window.confirm('هل تريد حذف هذا الريلز نهائياً؟'))return;try{const url=videoUrl||reel.data.video_url||'';const marker='/storage/v1/object/public/reels/';const path=url.includes(marker)?decodeURIComponent(url.split(marker)[1].split('?')[0]):null;if(path){const rm=await sb.storage.from('reels').remove([path]);if(rm.error)console.warn('storage delete:',rm.error)}const del=await sb.from('reels').delete().eq('id',id).eq('author_id',u.id);if(del.error)throw del.error;card?.remove();toast('تم حذف الريلز بنجاح 🗑️')}catch(err){console.error(err);toast('تعذر حذف الريلز')}}
  async function loadReels(){const row=document.getElementById('reelsRow');if(!row||typeof sb==='undefined')return;row.innerHTML='<div class="reel-empty">جاري تحميل الريلز…</div>';try{const {data,error}=await sb.from('reels').select('id,author_id,video_url,caption,created_at').order('created_at',{ascending:false}).limit(30);if(error)throw error;if(!data?.length){row.innerHTML='<div class="reel-empty">لا توجد ريلز متاحة حالياً</div>';return}let names={};const ids=[...new Set(data.map(r=>r.author_id).filter(Boolean))];if(ids.length){const q=await sb.from('profiles').select('id,display_name').in('id',ids);(q.data||[]).forEach(p=>names[p.id]=p.display_name)}const u=await getCurrentUser();row.innerHTML=data.map(r=>`<article class="reel-card" data-reel-id="${esc(r.id)}"><video class="reel-video-preview" src="${esc(r.video_url)}" muted playsinline preload="metadata"></video><div class="reel-badge">🎬 ريلز</div><div class="reel-sound-hint">🔇 اضغط على الفيديو للصوت</div><div class="reel-overlay-info"><span class="reel-author">@${esc(names[r.author_id]||'مستخدم')}</span>${r.caption?`<div>${esc(r.caption)}</div>`:''}</div><div class="reel-actions"><button type="button" onclick="toggleReelLike('${esc(r.id)}',this)">❤️ <span class="reel-like-count">0</span></button><button type="button" onclick="openReelComments('${esc(r.id)}')">💬 <span class="reel-comment-count">0</span></button><button type="button" onclick="shareReel('${esc(r.id)}')">↗️</button>${u&&u.id===r.author_id?`<button type="button" class="reel-delete-btn" onclick="deleteReel('${esc(r.id)}','${esc(r.video_url)}',this.closest('.reel-card'))">🗑️</button>`:''}</div></article>`).join('');await loadReelCounts(data);setupAutoPreviewReels(row);setupReelGestures(row)}catch(error){console.error(error);row.innerHTML='<div class="reel-empty">تعذر تحميل الريلز. حاول فتح الصفحة مرة أخرى.</div>'}}
  async function loadReelCounts(rs){const ids=rs.map(r=>r.id);if(!ids.length)return;const [{data:l},{data:c}]=await Promise.all([sb.from('reel_likes').select('reel_id').in('reel_id',ids),sb.from('reel_comments').select('reel_id').in('reel_id',ids)]);const lc={},cc={};(l||[]).forEach(x=>lc[x.reel_id]=(lc[x.reel_id]||0)+1);(c||[]).forEach(x=>cc[x.reel_id]=(cc[x.reel_id]||0)+1);rs.forEach(r=>{const el=document.querySelector(`.reel-card[data-reel-id="${r.id}"]`);if(el){el.querySelector('.reel-like-count').textContent=lc[r.id]||0;el.querySelector('.reel-comment-count').textContent=cc[r.id]||0}})}
  function setupReelGestures(row){let y=0;row.ontouchstart=e=>{if(e.touches.length===1)y=e.touches[0].clientY};row.ontouchend=e=>{const dy=e.changedTouches[0].clientY-y;if(Math.abs(dy)>45)row.scrollBy({top:dy<0?innerHeight:-innerHeight,behavior:'smooth'})}}
  window.setupReelGestures=setupReelGestures;window.deleteReel=deleteReel;window.openReelsSection=function(){const s=document.getElementById('reelsSection');if(!s)return;s.classList.add('is-open');document.body.classList.add('reels-view-open');loadReels()};window.closeReelsSection=function(){const s=document.getElementById('reelsSection');if(!s)return;s.classList.remove('is-open');document.body.classList.remove('reels-view-open');document.getElementById('reelsRow')?.scrollTo({top:0})};
  window.toggleReelLike=async function(id,b){const u=await getCurrentUser();if(!u){toast('سجل الدخول أولاً');return}const {data:ex}=await sb.from('reel_likes').select('reel_id').eq('reel_id',id).eq('user_id',u.id).maybeSingle();if(ex)await sb.from('reel_likes').delete().eq('reel_id',id).eq('user_id',u.id);else await sb.from('reel_likes').insert({reel_id:id,user_id:u.id});const {count}=await sb.from('reel_likes').select('*',{count:'exact',head:true}).eq('reel_id',id);b.querySelector('.reel-like-count').textContent=count||0};
  window.shareReel=async function(id){const u=await getCurrentUser();if(!u){toast('سجل الدخول أولاً');return}const {error}=await sb.from('reel_shares').upsert({reel_id:id,user_id:u.id},{onConflict:'reel_id,user_id'});if(error){toast('تعذر تسجيل المشاركة');return}const {data}=await sb.from('reels').select('video_url').eq('id',id).single();try{if(data?.video_url)await navigator.clipboard.writeText(data.video_url);toast('تمت المشاركة ونسخ الرابط ↗️')}catch{toast('تم تسجيل المشاركة ↗️')}};
  window.loadReels=loadReels;window.openFullReel=function(v){if(v)playOnly(v)};document.addEventListener('DOMContentLoaded',()=>setTimeout(loadReels,700));
})();