(function(){
const $=id=>document.getElementById(id);
const sections=[
['حسابك',[['👤','مركز الحسابات','إدارة حسابك ومعلومات تسجيل الدخول'],['💳','الاشتراكات','إدارة الاشتراكات والمدفوعات']]],
['الأدوات والموارد',[['🛡️','التحقق من الخصوصية','راجع إعدادات الخصوصية والأمان'],['♧','مركز العائلة','إدارة تجربة العائلة'],['📋','التفضيلات','تخصيص تجربتك وإدارة ما يظهر لك'],['💬','إعدادات التفاعلات','إدارة التعليقات والتفاعلات'],['🔔','الإشعارات','اختر ما تريد أن يصلك من إشعارات'],['♿','إمكانية الوصول','خيارات العرض وإمكانية الوصول'],['📌','تثبيت علامات التبويب','تخصيص علامات التبويب'],['🌐','اللغة والمنطقة','اللغة والمنطقة والتنسيقات'],['▣','الوسائط','إعدادات الصور والفيديو'],['◷','إدارة الوقت','تذكيرات وقت الاستخدام'],['▣','المتصفح','إعدادات التصفح داخل التطبيق'],['🌙','الوضع المظلم','تفعيل أو إيقاف الوضع المظلم'],['📷','اقتراحات مشاركة اليوم بالكاميرا','خيارات مشاركة الصور بالكاميرا'],['⚗️','صلاحية الوصول المبكر إلى الميزات','تجربة الميزات الجديدة قبل الجميع']]],
['الجمهور وإمكانية الرؤية',[['🔒','قفل الملف الشخصي','تحكم في الأشخاص الذين يمكنهم رؤية ملفك'],['👤','تفاصيل الملف الشخصي','تعديل معلومات ملفك الشخصي'],['◉','تنشيط الوضع الاحترافي','أدوات إضافية لصنّاع المحتوى'],['👥','كيفية العثور عليك والتواصل معك','تحكم في طرق العثور عليك'],['▤','المنشورات','تحديد جمهور منشوراتك'],['⊕','القصص','إدارة جمهور القصص'],['▣','ريلز','إعدادات الريلز'],['▣','المتابعون والمحتوى العام','إدارة المتابعين والمحتوى العام'],['🏷️','الملف الشخصي والإشارات','التحكم في الإشارات'],['🚫','الحظر','إدارة الحسابات المحظورة'],['👥','حالة النشاط','التحكم في ظهور حالة نشاطك']]],
['عمليات الدفع',[['💰','عمليات الدفع','إدارة معلومات وطرق الدفع'],['▣','عمليات الدفع الخاصة بالإعلانات','إدارة دفع الإعلانات']]],
['نشاطاتك',[['☷','سجل النشاطات','مراجعة نشاطاتك والمحتوى الذي تمت الإشارة إليك فيه'],['📱','أذونات الجهاز','إدارة صلاحيات الكاميرا والميكروفون وغيرها'],['▦','التطبيقات ومواقع الويب','إدارة التطبيقات المرتبطة'],['🧰','تطبيقات دمج الأعمال','إدارة تكاملات الأعمال'],['❓','تعرف على كيفية إدارة معلوماتك','معلومات عن البيانات والخصوصية']]],
['معايير المجتمع والسياسات القانونية',[['📜','معايير المجتمع','معرفة قواعد مجتمع مدى'],['⚖️','الشروط والسياسات','الشروط وسياسة الخصوصية']]]
];
function render(){if($('settingsPage'))return;const p=document.createElement('section');p.id='settingsPage';p.hidden=true;p.innerHTML=`<header class="settings-head"><button class="back" id="settingsBack">›</button><h2>الإعدادات والخصوصية</h2></header><div class="settings-search">⌕ <input id="settingsSearch" placeholder="بحث في الإعدادات"></div><div id="settingsList"></div><div class="settings-footer">MADA · الإعدادات والخصوصية</div>`;document.body.appendChild(p);$('settingsBack').onclick=close;build();$('settingsSearch').oninput=e=>build(e.target.value.trim())}
function build(q=''){const box=$('settingsList');if(!box)return;box.innerHTML='';const term=q.toLowerCase();sections.forEach((s,si)=>{const items=s[1].filter(x=>(x[1]+' '+x[2]).toLowerCase().includes(term));if(!items.length)return;const sec=document.createElement('div');sec.className='settings-section';sec.innerHTML='<h3>'+s[0]+'</h3>';items.forEach(x=>{const b=document.createElement('button');b.className='settings-item';b.innerHTML=`<span class="settings-icon">${x[0]}</span><span class="settings-text"><b>${x[1]}</b><span>${x[2]}</span></span><span class="settings-arrow">‹</span>`;b.onclick=()=>action(x[1]);sec.appendChild(b)});box.appendChild(sec);if(si<sections.length-1)box.insertAdjacentHTML('beforeend','<div class="settings-divider"></div>')})}
function action(name){if(name==='الوضع المظلم'){const dark=!document.body.classList.contains('dark');if(typeof applyTheme==='function')applyTheme(dark);else document.body.classList.toggle('dark',dark);return}if(name==='تفاصيل الملف الشخصي'&&window.openProfile){close();window.openProfile();return}if(name==='الإشعارات'&&typeof showModal==='function'){close();showModal('🔔 الإشعارات','<div class="empty">إعدادات الإشعارات متاحة هنا.</div>');return}if(typeof showModal==='function'){showModal(name,'<div class="empty">تم فتح إعداد <b>'+name+'</b>.<br><small>سنربط هذا الخيار بإعداداته التفصيلية في الخطوة التالية.</small></div>')}}
function open(){render();$('settingsPage').hidden=false;document.body.style.overflow='hidden'}function close(){if($('settingsPage'))$('settingsPage').hidden=true;document.body.style.overflow=''}
window.MadaSettings={open,close};document.addEventListener('DOMContentLoaded',()=>{const bind=()=>{['menuBottom','menuBtn'].forEach(id=>{const b=$(id);if(b&&!b.dataset.settingsBound){b.dataset.settingsBound='1';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();open()},true)}})};bind();setTimeout(bind,500)})
})();
