const Social={
  async profile(id){const{data}=await sb.from('profiles').select('id,username,display_name,avatar_url,bio,role,is_banned,created_at').eq('id',id).single();if(!data)return null;const[{count:followers},{count:following}]=await Promise.all([sb.from('follows').select('*',{count:'exact',head:true}).eq('following_id',id),sb.from('follows').select('*',{count:'exact',head:true}).eq('follower_id',id)]);return{...data,followers:followers||0,following:following||0}},
  async relation(id){const{data}=await sb.from('friendships').select('id,requester_id,addressee_id,status').or(`and(requester_id.eq.${user.id},addressee_id.eq.${id}),and(requester_id.eq.${id},addressee_id.eq.${user.id})`).maybeSingle();return data},
  async following(id){const{data}=await sb.from('follows').select('follower_id').eq('follower_id',user.id).eq('following_id',id).maybeSingle();return !!data},
  async toggleFollow(id){if(await this.following(id))await sb.from('follows').delete().eq('follower_id',user.id).eq('following_id',id);else await sb.from('follows').insert({follower_id:user.id,following_id:id})},
  async requests(){const{data}=await sb.from('friendships').select('id,requester_id,status,created_at,profiles!friendships_requester_id_fkey(display_name,avatar_url)').eq('addressee_id',user.id).eq('status','pending').order('created_at',{ascending:false});return data||[]},
  async suggestions(){const{data:friends}=await sb.from('friendships').select('requester_id,addressee_id').or(`requester_id.eq.${user.id},addressee_id.eq.${user.id}`).eq('status','accepted');const excluded=new Set([user.id]);(friends||[]).forEach(r=>excluded.add(r.requester_id===user.id?r.addressee_id:r.requester_id));const{data}=await sb.from('profiles').select('id,display_name,avatar_url,bio').not('id','in',`(${[...excluded].join(',')})`).limit(20);return data||[]},
  async openProfile(id){const p=await this.profile(id);if(!p)return;const r=await this.relation(id),f=await this.following(id);let action='';if(r?.status==='accepted')action='<span class="social-badge">✓ أصدقاء</span>';else if(r?.status==='pending')action=r.requester_id===user.id?'<span class="social-badge">⏳ طلب مُرسل</span>':'<button class="social-btn" data-accept="'+id+'">قبول طلب الصداقة</button>';else action='<button class="social-btn" data-friend="'+id+'">👥 إضافة صديق</button>';showModal('👤 الملف الشخصي',`<div class="profile-page"><div class="profile-cover"></div><div class="profile-avatar">${esc((p.display_name||'م').charAt(0))}</div><h2>${esc(p.display_name)} ${p.role==='admin'?'👑':''}</h2><p>${esc(p.bio||'مرحبًا بك في Mada')}</p><div class="profile-stats"><b>${p.followers}<small>متابع</small></b><b>${p.following}<small>يتابع</small></b></div><div class="social-actions">${action}<button class="social-btn ${f?'following':''}" data-follow="${id}">${f?'✓ يتابعك / إلغاء المتابعة':'➕ متابعة'}</button></div></div>`);const modal=$('modal');modal.querySelector('[data-follow]')?.addEventListener('click',async()=>{await this.toggleFollow(id);this.openProfile(id)});modal.querySelector('[data-friend]')?.addEventListener('click',async()=>{await sb.from('friendships').insert({requester_id:user.id,addressee_id:id,status:'pending'});this.openProfile(id)});modal.querySelector('[data-accept]')?.addEventListener('click',async()=>{const rr=await this.relation(id);if(rr)await sb.from('friendships').update({status:'accepted'}).eq('id',rr.id);this.openProfile(id)})},
  async center(){showModal('👥 الأصدقاء والمجتمع',`<div class="social-tabs"><button id="reqTab">طلبات الصداقة</button><button id="sugTab">اقتراحات</button><button id="findTab">بحث</button></div><div id="socialPanel">جاري التحميل…</div>`);const renderReq=async()=>{const d=await this.requests();$('socialPanel').innerHTML=d.length?d.map(x=>`<div class="user-row"><div class="avatar">${esc((x.profiles?.display_name||'م').charAt(0))}</div><div class="user-info"><b>${esc(x.profiles?.display_name||'مستخدم')}</b><small>يريد أن يكون صديقك</small></div><button class="social-btn" data-accept-req="${x.id}">قبول</button></div>`).join(''):'<div class="empty">لا توجد طلبات جديدة.</div>';$('socialPanel').onclick=async e=>{const b=e.target.closest('[data-accept-req]');if(!b)return;await sb.from('friendships').update({status:'accepted'}).eq('id',b.dataset.acceptReq);renderReq()}};const renderSug=async()=>{const d=await this.suggestions();$('socialPanel').innerHTML=d.length?d.map(x=>`<div class="user-row"><div class="avatar">${esc((x.display_name||'م').charAt(0))}</div><div class="user-info"><b>${esc(x.display_name)}</b><small>${esc(x.bio||'عضو في Mada')}</small></div><button class="social-btn" data-open="${x.id}">عرض</button></div>`).join(''):'<div class="empty">لا توجد اقتراحات حاليًا.</div>';$('socialPanel').onclick=e=>{const b=e.target.closest('[data-open]');if(b)this.openProfile(b.dataset.open)}};const renderFind=()=>{$('socialPanel').innerHTML='<input id="peopleQ" class="social-input" placeholder="ابحث عن شخص…"><button id="peopleSearch" class="primary wide">بحث</button><div id="peopleResults"></div>';$('peopleSearch').onclick=async()=>{const q=$('peopleQ').value.trim();if(q.length<2)return;const d=await searchUsers(q);$('peopleResults').innerHTML=d.map(x=>`<div class="user-row"><div class="avatar">${esc((x.display_name||'م').charAt(0))}</div><div class="user-info"><b>${esc(x.display_name)}</b></div><button class="social-btn" data-open="${x.id}">فتح</button></div>`).join('')}};$('reqTab').onclick=renderReq;$('sugTab').onclick=renderSug;$('findTab').onclick=renderFind;renderReq()},
  realtime(){sb.channel('social-notifications').on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications',filter:`user_id=eq.${user.id}`},p=>{if(p.new.type==='friend_request'||p.new.type==='follow'||p.new.title?.includes('صداقة')||p.new.title?.includes('متابع')){const n=$('notifyNav');if(n)n.classList.add('has-new');}}).subscribe()}
};
window.Social=Social;
