const currentUser=()=>window.madaUser?.();
const Social={
  async profile(id){const{data}=await sb.from('profiles').select('id,username,display_name,avatar_url,bio,role,is_banned,created_at').eq('id',id).single();if(!data)return null;const[{count:followers},{count:following}]=await Promise.all([sb.from('follows').select('*',{count:'exact',head:true}).eq('following_id',id),sb.from('follows').select('*',{count:'exact',head:true}).eq('follower_id',id)]);return{...data,followers:followers||0,following:following||0}},
  async relation(id){const u=currentUser();if(!u)return null;const{data}=await sb.from('friendships').select('id,requester_id,addressee_id,status').or(`and(requester_id.eq.${u.id},addressee_id.eq.${id}),and(requester_id.eq.${id},addressee_id.eq.${u.id})`).maybeSingle();return data},
  async following(id){const u=currentUser();if(!u)return false;const{data}=await sb.from('follows').select('follower_id').eq('follower_id',u.id).eq('following_id',id).maybeSingle();return !!data},
  async toggleFollow(id){const u=currentUser();if(!u)return;if(await this.following(id))await sb.from('follows').delete().eq('follower_id',u.id).eq('following_id',id);else await sb.from('follows').insert({follower_id:u.id,following_id:id})},
  async requests(){const u=currentUser();if(!u)return[];const{data}=await sb.from('friendships').select('id,requester_id,status,created_at,profiles!friendships_requester_id_fkey(display_name,avatar_url)').eq('addressee_id',u.id).eq('status','pending').order('created_at',{ascending:false});return data||[]},
  async friends(){const u=currentUser();if(!u)return[];const[a,b]=await Promise.all([sb.from('friendships').select('id,requester_id,addressee_id').eq('requester_id',u.id).eq('status','accepted'),sb.from('friendships').select('id,requester_id,addressee_id').eq('addressee_id',u.id).eq('status','accepted')]);const rows=[...(a.data||[]),...(b.data||[])],ids=[...new Set(rows.map(x=>x.requester_id===u.id?x.addressee_id:x.requester_id))];if(!ids.length)return[];const{data}=await sb.from('profiles').select('id,display_name,username,avatar_url,bio').in('id',ids);return(data||[]).map(p=>({...p,friendship:rows.find(x=>(x.requester_id===p.id||x.addressee_id===p.id))}))},
  async suggestions(){const u=currentUser();if(!u)return[];const{data:friends}=await sb.from('friendships').select('requester_id,addressee_id').or(`requester_id.eq.${u.id},addressee_id.eq.${u.id}`).eq('status','accepted');const excluded=new Set([u.id]);(friends||[]).forEach(r=>excluded.add(r.requester_id===u.id?r.addressee_id:r.requester_id));const{data}=await sb.from('profiles').select('id,display_name,avatar_url,bio').not('id','in',`(${[...excluded].join(',')})`).limit(20);return data||[]},
  async openProfile(id){if(window.ProfileUI?.open)return window.ProfileUI.open(id);const p=await this.profile(id);if(p&&window.showModal)showModal('👤 الملف الشخصي',`<div class="profile-page"><div class="profile-avatar">${esc((p.display_name||'م').charAt(0))}</div><h2>${esc(p.display_name)}</h2><p>${esc(p.bio||'مرحبًا بك في Mada')}</p></div>`)},
  async sendRequest(id){const u=currentUser();if(!u||!id||id===u.id)return;const r=await this.relation(id);if(r?.status==='accepted')return alert('أنتما أصدقاء بالفعل.');if(r?.status==='pending')return alert(r.requester_id===u.id?'تم إرسال طلب الصداقة بالفعل.':'لديك طلب صداقة وارد بالفعل.');const{error}=await sb.from('friendships').insert({requester_id:u.id,addressee_id:id,status:'pending'});if(error)return alert('تعذر إرسال طلب الصداقة: '+error.message);this.center('requests')},
  async respond(id,accept){const u=currentUser();if(!u)return;const q=accept?sb.from('friendships').update({status:'accepted',updated_at:new Date().toISOString()}).eq('id',id).eq('addressee_id',u.id).eq('status','pending'):sb.from('friendships').delete().eq('id',id).eq('addressee_id',u.id).eq('status','pending');const{error}=await q;if(error)return alert('تعذر تحديث طلب الصداقة: '+error.message);this.center('requests')},
  async removeFriend(id){const r=await this.relation(id);if(!r||r.status!=='accepted')return;if(!confirm('هل تريد إزالة هذا الصديق؟'))return;const{error}=await sb.from('friendships').delete().eq('id',r.id);if(error)return alert('تعذر إزالة الصديق: '+error.message);this.center('friends')},
  async cancelRequest(id){const u=currentUser();if(!u)return;const r=await this.relation(id);if(!r||r.status!=='pending'||r.requester_id!==u.id)return;const{error}=await sb.from('friendships').delete().eq('id',r.id).eq('requester_id',u.id).eq('addressee_id',id);if(error)return alert('تعذر إلغاء الطلب: '+error.message);this.center('sent')},
  async center(tab='requests'){const u=currentUser();if(!u)return;showModal('👥 الأصدقاء والمجتمع',`<div class="social-tabs"><button id="reqTab">طلبات الصداقة</button><button id="friendsTab">أصدقائي</button><button id="sentTab">طلبات أرسلتها</button><button id="sugTab">اقتراحات</button><button id="findTab">بحث</button></div><div id="socialPanel">جاري التحميل…</div>`);const panel=$('socialPanel');const renderReq=async()=>{const d=await this.requests();panel.innerHTML=d.length?d.map(x=>`<div class="user-row"><div class="avatar">${x.profiles?.avatar_url?`<img src="${esc(x.profiles.avatar_url)}">`:esc((x.profiles?.display_name||'م').charAt(0))}</div><div class="user-info"><b>${esc(x.profiles?.display_name||'مستخدم')}</b><small>يريد أن يكون صديقك</small></div><button class="social-btn" data-accept-req="${x.id}">قبول</button><button class="social-btn" data-reject-req="${x.id}">رفض</button></div>`).join(''):'<div class="empty">لا توجد طلبات جديدة.</div>';panel.onclick=async e=>{const a=e.target.closest('[data-accept-req]');if(a)return this.respond(a.dataset.acceptReq,true);const r=e.target.closest('[data-reject-req]');if(r)return this.respond(r.dataset.rejectReq,false);const o=e.target.closest('[data-open]');if(o)return this.openProfile(o.dataset.open)}};
  const renderFriends=async()=>{const d=await this.friends();panel.innerHTML=d.length?d.map(x=>`<div class="user-row"><button class="avatar" data-open="${x.id}">${x.avatar_url?`<img src="${esc(x.avatar_url)}">`:esc((x.display_name||'م').charAt(0))}</button><div class="user-info"><b>${esc(x.display_name||'مستخدم')}</b><small>${esc(x.username?'@'+x.username:(x.bio||'صديق في Mada'))}</small></div><button class="social-btn" data-open="${x.id}">فتح</button><button class="social-btn" data-remove="${x.id}">إزالة</button></div>`).join(''):'<div class="empty">لا يوجد أصدقاء حتى الآن.</div>';panel.onclick=async e=>{const r=e.target.closest('[data-remove]');if(r)return this.removeFriend(r.dataset.remove);const o=e.target.closest('[data-open]');if(o)return this.openProfile(o.dataset.open)}};
  const renderSent=async()=>{const{data}=await sb.from('friendships').select('id,addressee_id,created_at,profiles!friendships_addressee_id_fkey(display_name,avatar_url)').eq('requester_id',u.id).eq('status','pending').order('created_at',{ascending:false});panel.innerHTML=data?.length?data.map(x=>`<div class="user-row"><div class="avatar">${x.profiles?.avatar_url?`<img src="${esc(x.profiles.avatar_url)}">`:esc((x.profiles?.display_name||'م').charAt(0))}</div><div class="user-info"><b>${esc(x.profiles?.display_name||'مستخدم')}</b><small>طلب صداقة مُرسل</small></div><button class="social-btn" data-cancel="${x.addressee_id}">إلغاء الطلب</button></div>`).join(''):'<div class="empty">لا توجد طلبات مرسلة.</div>';panel.onclick=async e=>{const c=e.target.closest('[data-cancel]');if(c)return this.cancelRequest(c.dataset.cancel)}};
  const renderSug=async()=>{const d=await this.suggestions();panel.innerHTML=d.length?d.map(x=>`<div class="user-row"><button class="avatar" data-open="${x.id}">${x.avatar_url?`<img src="${esc(x.avatar_url)}">`:esc((x.display_name||'م').charAt(0))}</button><div class="user-info"><b>${esc(x.display_name||'مستخدم')}</b><small>${esc(x.bio||'اقتراح صديق جديد')}</small></div><button class="social-btn" data-friend="${x.id}">👥 إضافة صديق</button></div>`).join(''):'<div class="empty">لا توجد اقتراحات حاليًا.</div>';panel.onclick=async e=>{const f=e.target.closest('[data-friend]');if(f)return this.sendRequest(f.dataset.friend);const o=e.target.closest('[data-open]');if(o)return this.openProfile(o.dataset.open)}};
  const renderFind=()=>{panel.innerHTML='<input id="peopleQ" class="social-input" placeholder="ابحث عن شخص…"><button id="peopleSearch" class="primary wide">بحث</button><div id="peopleResults"></div>';$('peopleSearch').onclick=async()=>{const q=$('peopleQ').value.trim();if(q.length<2)return;const d=await searchUsers(q);$('peopleResults').innerHTML=d.length?d.map(x=>`<div class="user-row"><div class="avatar">${x.avatar_url?`<img src="${esc(x.avatar_url)}">`:esc((x.display_name||'م').charAt(0))}</div><div class="user-info"><b>${esc(x.display_name||'مستخدم')}</b></div><button class="social-btn" data-open="${x.id}">فتح</button></div>`).join(''):'<div class="empty">لا توجد نتائج.</div>';};panel.onclick=e=>{const o=e.target.closest('[data-open]');if(o)this.openProfile(o.dataset.open)}};
  $('reqTab').onclick=renderReq;$('friendsTab').onclick=renderFriends;$('sentTab').onclick=renderSent;$('sugTab').onclick=renderSug;$('findTab').onclick=renderFind;if(tab==='friends')return renderFriends();if(tab==='sent')return renderSent();if(tab==='suggestions')return renderSug();if(tab==='search')return renderFind();return renderReq()},
  realtime(){const u=currentUser();if(!u)return;sb.channel('social-notifications').on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications',filter:`user_id=eq.${u.id}`},p=>{if(p.new.type==='friend_request'||p.new.type==='follow'||p.new.title?.includes('صداقة')||p.new.title?.includes('متابع')){const n=$('notifyNav');if(n)n.classList.add('has-new');}}).subscribe()}
};
window.Social=Social;