(function(){
'use strict';
if(window.__MADA_VERIFICATION_UI_V3)return;window.__MADA_VERIFICATION_UI_V3=true;
const sb=()=>window.MADA_SUPABASE_CLIENT||window.supabase.createClient(window.MADA_SUPABASE_URL,window.MADA_SUPABASE_KEY);
const cache=new Map(),pending=new Set();
function active(p){if(!p?.is_verified)return false;if(p.verification_type==='premium'&&p.verification_expires_at&&new Date(p.verification_expires_at)<=new Date())return false;return true}
function badge(p){if(!active(p))return '';const premium=p.verification_type==='premium';return `<span class="mada-verified-badge ${premium?'premium':''}" role="img" aria-label="${premium?'حساب موثق Premium':'حساب موثق'}" title="${premium?'حساب موثق Premium':'حساب موثق'}"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2.4l2.05 1.2 2.36-.08 1.2 2.05 2.05 1.2-.08 2.36L20.8 11l.08 2.36-2.05 1.2-1.2 2.05-2.36-.08L12 17.6l-2.05-1.07-2.36.08-1.2-2.05-2.05-1.2L4.4 11l-.08-2.36 2.05-1.2 1.2.08 1.2.08L12 2.4z"/><path class="check" d="M8 11.8l2.45 2.45L16.5 8.2"/></svg></span>`}
function getId(el){for(const a of ['data-profile-id','data-user-id','data-author-id','data-profile','data-user','data-author','data-sender-id']){const v=el?.getAttribute?.(a);if(v)return v}return null}
const ATTR='[data-profile-id],[data-user-id],[data-author-id],[data-profile],[data-user],[data-author],[data-sender-id]';
const TEXT='.post-name,.comment b,.reply b,.user-info b,.conversation-list .user-info b,.message-author,.notification-user,.profile-name';
function collect(root){const out=[];if(!root)return out;if(root.nodeType===1){if(root.matches?.(ATTR+':not(.avatar)'))out.push(root);root.querySelectorAll?.(ATTR+':not(.avatar)').forEach(x=>out.push(x));root.querySelectorAll?.(TEXT).forEach(x=>{if(!x.classList.contains('avatar')&&!x.dataset.madaVerifyTarget)out.push(x)});if(root.matches?.(TEXT)&&!root.classList.contains('avatar')&&!root.dataset.madaVerifyTarget)out.push(root)}return [...new Set(out)]}
function addIdsNearby(root){if(!root?.querySelectorAll)return;root.querySelectorAll('[data-profile]').forEach(x=>{const uid=getId(x);if(!uid)return;const holder=x.closest('.post-head,.comment,.reply,.user-row,.conversation-row,.notification-item');const n=holder?.querySelector('.post-name,.comment-name,.reply-name,.user-info b,.message-author,.notification-user');if(n&&!getId(n))n.setAttribute('data-profile',uid)})}
async function fetchProfiles(ids){const missing=ids.filter(id=>!cache.has(id)&&!pending.has(id));if(!missing.length)return;missing.forEach(id=>pending.add(id));try{for(let i=0;i<missing.length;i+=80){const r=await sb().from('profiles').select('id,is_verified,verification_type,verification_expires_at').in('id',missing.slice(i,i+80));(r.data||[]).forEach(p=>cache.set(p.id,p))}}finally{missing.forEach(id=>pending.delete(id))}}
function mark(el,p){if(!el||el.classList.contains('avatar'))return;const id=getId(el);if(!id)return;el.dataset.madaVerifyTarget='1';el.querySelectorAll(':scope > .mada-verified-badge:not(.admin)').forEach(x=>x.remove());const b=badge(p);if(b&&!el.querySelector(':scope > .mada-verified-badge:not(.admin)'))el.insertAdjacentHTML('beforeend',b)}
async function decorate(root){addIdsNearby(root);const els=collect(root),ids=[...new Set(els.map(getId).filter(Boolean))];if(!ids.length)return;await fetchProfiles(ids);els.forEach(el=>mark(el,cache.get(getId(el))))}
window.MadaVerification=Object.assign(window.MadaVerification||{},{badge,refresh:()=>{cache.clear();return decorate(document)}});
function start(){decorate(document);if(!document.body)return;let roots=[],timer=0;const queue=()=>{if(timer)return;timer=setTimeout(async()=>{timer=0;const rs=[...new Set(roots)];roots=[];for(const root of rs)await decorate(root)},120)};new MutationObserver(ms=>{for(const m of ms){for(const n of m.addedNodes||[]){if(n.nodeType===1&&!n.matches?.('.mada-verified-badge'))roots.push(n)}}if(roots.length)queue()}).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();