package com.mada.app;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.os.*;import android.provider.Settings;import android.view.*;import android.view.animation.*;import android.widget.*;import android.text.TextUtils;import okhttp3.*;import org.json.*;import java.util.concurrent.*;

public class BuzzService extends Service{
 static final String URL="https://eclnddvupggxyythtpkv.supabase.co";static final String KEY="sb_publishable_FqI5heK77syr-3QHh2LPHg_E82vbq-0";
 static final String BG_CHANNEL="mada_bg",BUZZ_CHANNEL="mada_buzz_high";
 OkHttpClient client;WebSocket ws;WindowManager wm;View overlay;String uid,token,refresh;SharedPreferences sp;Handler h=new Handler(Looper.getMainLooper());boolean reconnecting=false;int joinRef=0;
 Runnable refreshTask=()->refreshSession();Runnable heartbeat=()->sendHeartbeat();
 @Override public void onCreate(){super.onCreate();sp=getSharedPreferences("mada",0);client=new OkHttpClient.Builder().pingInterval(25,TimeUnit.SECONDS).build();createChannels();startForeground(7,notification("جاري تشغيل حماية Buzz..."));loadCredentials();connect();}
 Notification notification(String text){Intent i=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,0,i,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);return new Notification.Builder(this,BG_CHANNEL).setSmallIcon(android.R.drawable.ic_dialog_info).setContentTitle("Mada Buzz").setContentText(text).setContentIntent(pi).setOngoing(true).build();}
 void updateNotification(String text){try{((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(7,notification(text));}catch(Exception ignored){}}
 void createChannels(){if(Build.VERSION.SDK_INT>=26){NotificationManager n=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);n.createNotificationChannel(new NotificationChannel(BG_CHANNEL,"Mada Buzz",NotificationManager.IMPORTANCE_LOW));NotificationChannel b=new NotificationChannel(BUZZ_CHANNEL,"Buzz",NotificationManager.IMPORTANCE_HIGH);b.setDescription("تنبيهات Buzz المنبثقة");b.enableVibration(true);b.setVibrationPattern(new long[]{0,180,70,180,70,320});b.setLockscreenVisibility(Notification.VISIBILITY_PUBLIC);n.createNotificationChannel(b);}}
 void loadCredentials(){token=sp.getString("access","");refresh=sp.getString("refresh","");uid=sp.getString("uid","");}
 void connect(){loadCredentials();if(TextUtils.isEmpty(token)||TextUtils.isEmpty(uid)){updateNotification("افتح Mada لتفعيل Buzz");return;}reconnecting=false;HttpUrl u=HttpUrl.parse(URL+"/realtime/v1/websocket").newBuilder().addQueryParameter("apikey",KEY).addQueryParameter("vsn","1.0.0").build();Request r=new Request.Builder().url(u).build();ws=client.newWebSocket(r,new WebSocketListener(){@Override public void onOpen(WebSocket s,Response r){try{joinRef++;JSONObject cfg=new JSONObject();cfg.put("broadcast",new JSONObject().put("ack",false).put("self",false));cfg.put("presence",new JSONObject().put("enabled",false));cfg.put("postgres_changes",new JSONArray().put(new JSONObject().put("event","INSERT").put("schema","public").put("table","messages").put("filter","message_type=eq.buzz")));JSONObject payload=new JSONObject().put("config",cfg).put("access_token",token);String jr=String.valueOf(joinRef);JSONObject join=new JSONObject().put("topic","realtime:public:messages").put("event","phx_join").put("payload",payload).put("ref",jr).put("join_ref",jr);s.send(join.toString());h.removeCallbacks(heartbeat);h.postDelayed(heartbeat,20000);scheduleRefresh();updateNotification("Buzz يعمل في الخلفية");}catch(Exception e){updateNotification("تعذر الاتصال بخدمة Buzz");scheduleReconnect();}}
 @Override public void onMessage(WebSocket s,String text){try{JSONObject x=new JSONObject(text);String ev=x.optString("event");if("phx_reply".equals(ev)){JSONObject p=x.optJSONObject("payload");if(p!=null&&"error".equals(p.optString("status"))){updateNotification("رفض اتصال Buzz: "+p.optJSONObject("response"));scheduleReconnect();}return;}if("system".equals(ev)){JSONObject p=x.optJSONObject("payload");if(p!=null&&"error".equals(p.optString("status")))updateNotification("Realtime Buzz غير متصل");return;}if("phx_close".equals(ev)||"phx_error".equals(ev)){scheduleReconnect();return;}if(!"postgres_changes".equals(ev))return;JSONObject p=x.optJSONObject("payload");if(p==null)return;JSONObject data=p.optJSONObject("data");JSONObject row=data!=null?data.optJSONObject("record"):p.optJSONObject("record");if(row==null)return;if(!"buzz".equals(row.optString("message_type")))return;if(uid.equals(row.optString("sender_id")))return;showOverlay(row.optString("sender_id"));}catch(Exception ignored){}}
 @Override public void onFailure(WebSocket s,Throwable t,Response r){updateNotification("انقطع اتصال Buzz — إعادة الاتصال...");scheduleReconnect();}});}
 void sendHeartbeat(){if(ws!=null){try{ws.send(new JSONObject().put("topic","phoenix").put("event","heartbeat").put("payload",new JSONObject()).put("ref",String.valueOf(System.currentTimeMillis())).toString());}catch(Exception ignored){}}h.postDelayed(heartbeat,20000);}
 void scheduleReconnect(){if(reconnecting)return;reconnecting=true;h.removeCallbacks(heartbeat);h.postDelayed(()->{reconnecting=false;connect();},5000);}
 void scheduleRefresh(){h.removeCallbacks(refreshTask);h.postDelayed(refreshTask,45*60*1000L);}
 void refreshSession(){loadCredentials();if(TextUtils.isEmpty(refresh)){scheduleRefreshRetry();return;}String encoded;try{encoded=java.net.URLEncoder.encode(refresh,"UTF-8");}catch(Exception e){scheduleRefreshRetry();return;}RequestBody body=RequestBody.create("grant_type=refresh_token&refresh_token="+encoded,MediaType.parse("application/x-www-form-urlencoded"));Request req=new Request.Builder().url(URL+"/auth/v1/token?grant_type=refresh_token").post(body).addHeader("apikey",KEY).addHeader("Content-Type","application/x-www-form-urlencoded").build();client.newCall(req).enqueue(new Callback(){public void onFailure(Call c,java.io.IOException e){scheduleRefreshRetry();}public void onResponse(Call c,Response r)throws java.io.IOException{try{String text=r.body()!=null?r.body().string():"";if(!r.isSuccessful())throw new Exception("refresh "+r.code());JSONObject o=new JSONObject(text);String a=o.optString("access_token","");String rr=o.optString("refresh_token",refresh);if(TextUtils.isEmpty(a))throw new Exception("missing access token");token=a;refresh=rr;sp.edit().putString("access",a).putString("refresh",rr).apply();if(ws!=null)ws.close(1000,"token refresh");ws=null;connect();}catch(Exception e){scheduleRefreshRetry();}}});}
 void scheduleRefreshRetry(){h.removeCallbacks(refreshTask);h.postDelayed(refreshTask,5*60*1000L);}
 void showOverlay(String senderId){h.post(()->{if(Build.VERSION.SDK_INT>=23&&!Settings.canDrawOverlays(this))return;String name="صديق Mada";try{Request r=new Request.Builder().url(URL+"/rest/v1/profiles?id=eq."+senderId+"&select=display_name").addHeader("apikey",KEY).addHeader("Authorization","Bearer "+token).build();client.newCall(r).enqueue(new Callback(){public void onFailure(Call c,java.io.IOException e){showBuzzNotification(name,senderId);}public void onResponse(Call c,Response r)throws java.io.IOException{String n=name;try{String text=r.body()!=null?r.body().string():"[]";JSONArray a=new JSONArray(text);if(a.length()>0){String q=a.getJSONObject(0).optString("display_name","");if(!TextUtils.isEmpty(q))n=q;}}catch(Exception ignored){}showBuzzNotification(n,senderId);}});}catch(Exception e){showBuzzNotification(name,senderId);}});}
 void showBuzzNotification(String name,String senderId){h.post(()->{try{NotificationManager n=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);Intent i=new Intent(this,MainActivity.class);i.putExtra("sender_id",senderId);i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_SINGLE_TOP|Intent.FLAG_ACTIVITY_CLEAR_TOP);int req=Math.abs((senderId+System.currentTimeMillis()).hashCode());PendingIntent pi=PendingIntent.getActivity(this,req,i,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);Notification.Builder b=new Notification.Builder(this,BUZZ_CHANNEL).setSmallIcon(android.R.drawable.ic_dialog_info).setContentTitle("📳 Buzz من "+name).setContentText("هـــزّك صديقك في Mada!").setStyle(new Notification.BigTextStyle().bigText("هـــزّك صديقك في Mada! اضغط لفتح المحادثة.")).setContentIntent(pi).setAutoCancel(true).setCategory(Notification.CATEGORY_MESSAGE).setPriority(Notification.PRIORITY_HIGH).setVibrate(new long[]{0,180,70,180,70,320});if(Build.VERSION.SDK_INT>=21)b.setTimeoutAfter(9000);n.notify(req,b.build());try{((android.os.Vibrator)getSystemService(VIBRATOR_SERVICE)).vibrate(new long[]{0,180,70,180,70,320},-1);}catch(Exception ignored){}}catch(Exception ignored){}});}
 void drawOverlay(String name,String senderId){ }
 void removeOverlay(){if(wm!=null&&overlay!=null){try{wm.removeView(overlay);}catch(Exception ignored){}overlay=null;}}
 @Override public int onStartCommand(Intent i,int f,int id){if(ws==null)connect();return START_STICKY;}
 @Override public void onDestroy(){h.removeCallbacks(refreshTask);h.removeCallbacks(heartbeat);removeOverlay();if(ws!=null)ws.close(1000,"stop");client.dispatcher().executorService().shutdown();super.onDestroy();}
 @Override public android.os.IBinder onBind(Intent i){return null;}
}
