package com.mada.app;

import android.app.*;import android.content.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import android.text.TextUtils;import okhttp3.*;import org.json.*;import java.util.concurrent.*;

public class BuzzService extends Service{
 static final String URL="https://eclnddvupggxyythtpkv.supabase.co";static final String KEY="sb_publishable_FqI5heK77syr-3QHh2LPHg_E82vbq-0";
 OkHttpClient client;WebSocket ws;WindowManager wm;View overlay;String uid,token;SharedPreferences sp;Handler h=new Handler(Looper.getMainLooper());
 @Override public void onCreate(){super.onCreate();sp=getSharedPreferences("mada",0);client=new OkHttpClient.Builder().pingInterval(25,TimeUnit.SECONDS).build();createChannel();startForeground(7,notification());connect();}
 Notification notification(){Intent i=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,0,i,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);return new Notification.Builder(this,"mada_bg").setSmallIcon(android.R.drawable.ic_dialog_info).setContentTitle("Mada Buzz").setContentText("حماية Buzz تعمل في الخلفية").setContentIntent(pi).setOngoing(true).build();}
 void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationManager n=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);n.createNotificationChannel(new NotificationChannel("mada_bg","Mada Buzz","LOW"));}}
 void connect(){token=sp.getString("access","");uid=sp.getString("uid","");if(TextUtils.isEmpty(token)||TextUtils.isEmpty(uid))return;HttpUrl u=HttpUrl.parse(URL+"/realtime/v1/websocket").newBuilder().addQueryParameter("apikey",KEY).addQueryParameter("vsn","1.0.0").build();Request r=new Request.Builder().url(u).build();ws=client.newWebSocket(r,new WebSocketListener(){@Override public void onOpen(WebSocket s,Response r){JSONObject cfg=new JSONObject();try{cfg.put("broadcast",new JSONObject().put("ack",false).put("self",false));cfg.put("presence",new JSONObject().put("key",uid));JSONArray pc=new JSONArray();pc.put(new JSONObject().put("event","INSERT").put("schema","public").put("table","messages").put("filter","message_type=eq.buzz"));cfg.put("postgres_changes",pc);JSONObject payload=new JSONObject().put("config",cfg).put("access_token",token);JSONObject join=new JSONObject().put("topic","realtime:public:messages").put("event","phx_join").put("payload",payload).put("ref","1");s.send(join.toString());}catch(Exception e){}}
 @Override public void onMessage(WebSocket s,String text){try{JSONObject x=new JSONObject(text);if(!"postgres_changes".equals(x.optString("event")))return;JSONObject rec=x.optJSONObject("payload");if(rec==null)rec=x;JSONObject data=rec.optJSONObject("data");if(data!=null)rec=data;JSONObject row=rec.optJSONObject("record");if(row==null)return;if(!"buzz".equals(row.optString("message_type")))return;if(uid.equals(row.optString("sender_id")))return;String sender=row.optString("sender_id");showOverlay(sender);}catch(Exception ignored){}}
 @Override public void onFailure(WebSocket s,Throwable t,Response r){h.postDelayed(()->connect(),5000);}});}
 void showOverlay(String senderId){h.post(()->{if(Build.VERSION.SDK_INT>=23&&!Settings.canDrawOverlays(this))return;String name="صديق Mada";try{Request r=new Request.Builder().url(URL+"/rest/v1/profiles?id=eq."+senderId+"&select=display_name").addHeader("apikey",KEY).addHeader("Authorization","Bearer "+token).build();client.newCall(r).enqueue(new Callback(){public void onFailure(Call c,java.io.IOException e){drawOverlay(name,senderId);}public void onResponse(Call c,Response r)throws java.io.IOException{String n=name;try{JSONArray a=new JSONArray(r.body().string());if(a.length()>0)n=a.getJSONObject(0).optString("display_name",name);}catch(Exception ignored){}drawOverlay(n,senderId);}});}catch(Exception e){drawOverlay(name,senderId);}});}
 void drawOverlay(String name,String senderId){h.post(()->{removeOverlay();wm=(WindowManager)getSystemService(WINDOW_SERVICE);LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(28,24,28,24);card.setGravity(Gravity.CENTER_HORIZONTAL);GradientDrawable bg=new GradientDrawable();bg.setColor(Color.WHITE);bg.setStroke(5,Color.rgb(245,158,11));bg.setCornerRadius(28);card.setBackground(bg);TextView head=new TextView(this);head.setText(name+"\n\nأرسل لك Buzz 📳");head.setTextColor(Color.rgb(20,35,60));head.setTextSize(24);head.setGravity(Gravity.CENTER);head.setTypeface(null,1);card.addView(head,new LinearLayout.LayoutParams(-1,-2));TextView body=new TextView(this);body.setText("📳\n\nهـــزّك صديقك في Mada!");body.setTextColor(Color.rgb(55,65,81));body.setTextSize(20);body.setGravity(Gravity.CENTER);body.setPadding(0,25,0,25);card.addView(body,new LinearLayout.LayoutParams(-1,-2));Button open=new Button(this);open.setText("فتح المحادثة");open.setTextSize(18);open.setTextColor(Color.WHITE);GradientDrawable ob=new GradientDrawable();ob.setColor(Color.rgb(245,158,11));ob.setCornerRadius(20);open.setBackground(ob);open.setOnClickListener(v->{removeOverlay();Intent i=new Intent(this,MainActivity.class);i.putExtra("sender_id",senderId);i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_SINGLE_TOP);startActivity(i);});card.addView(open,new LinearLayout.LayoutParams(-1,80));overlay=card;WindowManager.LayoutParams p=new WindowManager.LayoutParams((int)(getResources().getDisplayMetrics().widthPixels*.88f),WindowManager.LayoutParams.WRAP_CONTENT,Build.VERSION.SDK_INT>=26?WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY:WindowManager.LayoutParams.TYPE_PHONE,WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON|WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,android.graphics.PixelFormat.TRANSLUCENT);p.gravity=Gravity.CENTER;wm.addView(card,p);((android.os.Vibrator)getSystemService(VIBRATOR_SERVICE)).vibrate(new long[]{0,180,70,180,70,320},-1);h.postDelayed(this::removeOverlay,9000);});}
 void removeOverlay(){if(wm!=null&&overlay!=null){try{wm.removeView(overlay);}catch(Exception ignored){}overlay=null;}}
 @Override public int onStartCommand(Intent i,int f,int id){if(ws==null)connect();return START_STICKY;}
 @Override public void onDestroy(){removeOverlay();if(ws!=null)ws.close(1000,"stop");client.dispatcher().executorService().shutdown();super.onDestroy();}
 @Override public android.os.IBinder onBind(Intent i){return null;}
}
